### ISSUE TITLE
Milestone Rewards

### ISSUE THREAD

**Issue by Ryddag** [ProjectCeleste/Celeste_Server#1]
Issue: Can't enable Milestone rewards.

Cause : Function not implemented yet, planed soon.

**Comment by IamMidas** [comment]
Voting this up

**Comment by MisterAwoo** [comment]
These will definitely help in certain odds in the game ^^

**Comment by CharlieTheMcPro** [comment]
Been a while ey 👍

**Comment by KevinW1998** [comment]
This was the first issue ever posted and finally it has been fixed ;3

**Comment by MisterAwoo** [comment]
Nice! Good job team!

2018-01-08 21:06 GMT+01:00 Kevin Waldock <notifications@github.com>:
