### ISSUE TITLE
Whisper function in chat gives invalid gamertag.

### ISSUE THREAD

**Issue by ChewierElf** [ProjectCeleste/Celeste_Server#100]
When trying to use the /whisper or /w or right mouse click action on a gamer tag in game chat general the response I get is [gamertag name] is an invalid gamertag.

I can imagine this has no high priority or is coupled in the end with friends list/ pvp / coop and so.

Anyway just sharing the result
Hope this helps.

**Comment by Ryddag** [comment]
like pvp/coop/trade
