### ISSUE TITLE
Can't progress as Greeks because of a bug

### ISSUE THREAD

**Issue by DaantjuhNL** [ProjectCeleste/Celeste_Server#105]
Hey my brother is stuck with the quest "Bright light, Big city". He needed to do the quest of the mycean trader, which he did, yet it didn't progress the quest. Now he is stuck and can't do anything. This really needs to be fixed as at prevents people getting past level 3
![naamloos](https://user-images.githubusercontent.com/29275433/27012265-da0c7b6c-4ecc-11e7-8347-fdf3e601701f.png)

**Comment by Kaelion0** [comment]
Same problems

**Comment by Ryddag** [comment]
#101
