### ISSUE TITLE
objectives not being shown on screen

### ISSUE THREAD

**Issue by DaantjuhNL** [ProjectCeleste/Celeste_Server#106]
Take a look at the picture the objectives are not shown, it's a minor annoyance, but still would like it to be fixed. 
![naamloos](https://user-images.githubusercontent.com/29275433/27014102-185e0c6c-4ef2-11e7-99ff-d9262f77abb0.png)

**Comment by Ryddag** [comment]
hum... http://imgur.com/a/Swb4p
