### ISSUE TITLE
quests dont work or bugged

### ISSUE THREAD

**Issue by MrPSIHO13** [ProjectCeleste/Celeste_Server#108]
ABANDON  all quests 
LOG OUT or RESTART (close celeste launcher!!!)
should work :)

still test if 12h or more work proper

**Comment by MrPSIHO13** [comment]
all quests work as they
consumable trick still work

**Comment by Ryddag** [comment]
very usefull issue !!! what the point !!! and about consumable stop speaking of this glitch if you don't want to be be banned.

**Comment by MrPSIHO13** [comment]
i wont play anymore,great luck in future
