### ISSUE TITLE
Food Equals Villagers Not Working

### ISSUE THREAD

**Issue by musictopia** [ProjectCeleste/Celeste_Server#11]
After doing some other quests, I tried doing food equals villagers but the food gathered shows 0 no matter what.  This means there is no way to continue with the campaign.  I was level 5 when doing the quest.

**Comment by Ryddag** [comment]
Probably same cause has #8, so maybe fixed in the today deployment.

**Comment by musictopia** [comment]
The bad news is since I restarted the empire and did in order, the problem did not happen even before the update.  The only way to test it would be for somebody after completing the first quest is to try to complete some northern hold quests then try it.

**Comment by Ryddag** [comment]
Bug identified, fix ready.
