### ISSUE TITLE
Quest: Helping the generals

### ISSUE THREAD

**Issue by Daeveren** [ProjectCeleste/Celeste_Server#111]
This egyptian quest seems to have bugged on me, one of the objectives is not checked and I've completed all the related quests.
Questgiver: King Narmer in egyptian capital city
It shows me that I miss the General Ahapitep objective, but I've completed all the quests from him, have no active ones from him and he has no other quests to offer me.
Can't abandon the quest either.

![1](http://i.imgur.com/7ClW1SQ.png)

**Comment by Ryddag** [comment]
#110 

I will have to fix your save
