### ISSUE TITLE
Egypt Helping The Generals

### ISSUE THREAD

**Issue by Semperfi0817** [ProjectCeleste/Celeste_Server#112]
I have completed the 3 missions for both generals but cannot get the main reward. There is no complete option. There are also no other missions from the generals to accept.

**Comment by musictopia** [comment]
I completed the missions with no problem.  Once they were all completed, this showed as complete and i got the reward with no problem.  So I don't think there is an issue there.

**Comment by Ryddag** [comment]
I will fix your save (#111)
