### ISSUE TITLE
No quests work on the latest client

### ISSUE THREAD

**Issue by musictopia** [ProjectCeleste/Celeste_Server#114]
![problem](https://user-images.githubusercontent.com/29081369/27112743-c9b4c0c4-506d-11e7-8a69-4a948a950524.png)

the screenshot shows what happens.  Every quest i try has that problem.  It used to work.  However, after using the latest client, it gives the same issue.  All I did was unzip all the files from the patch notes in discord.

**Comment by musictopia** [comment]
The good news is there is a temporary workaround which is to run spartan.exe manually after logging in.  This means the no launcher file cannot be used.  I was told its an issue with how rms works.  talk to cad about it since he can explain to you.

**Comment by jiffyette** [comment]
i had no issues

**Comment by icen1** [comment]
same

**Comment by musictopia** [comment]
The client 1.20 fixes the problem.  Therefore, I am closing this issue.
