### ISSUE TITLE
Unable to launch game at all.

### ISSUE THREAD

**Issue by jlquincy** [ProjectCeleste/Celeste_Server#115]
I was using B101 and have always had to launch from Steam. The Steam launch no longer works with B112. I tried to got to B110 at the suggestion of another player but it seems to be the same one. I copied the files anyway and am still not able to launch the game. I get through the process of logging in then nothing happens after. Also, Windows Defender "Protects My PC" from Celeste Launcher. I have to click "More Info" then "Run Anyway"

**Comment by Ryddag** [comment]
Updated to B120
