### ISSUE TITLE
Chance that Moderate and Heavy treasures give 2-3 chests 

### ISSUE THREAD

**Issue by Jole1** [ProjectCeleste/Celeste_Server#116]
As far i can remember you could get more than one chest from those, can someone confrim this

**Comment by DaantjuhNL** [comment]
I thought the same, have always gotten 1 chest from a treasure, regardless of how well defended it was

**Comment by jiffyette** [comment]
1-3 used to be the norm, im sure this will change in time

**Comment by doddianca** [comment]
Just watched some old videos on Youtube, the single camp gave only 1, med. can give up to 2 and large tent can result in up to three chests awarded
