### ISSUE TITLE
Loot drops that should not be in the game

### ISSUE THREAD

**Issue by DaantjuhNL** [ProjectCeleste/Celeste_Server#119]
Am i supposed to be a bandit now?
![naamloos](https://user-images.githubusercontent.com/29275433/27150300-fac54948-5146-11e7-903e-51bb6aabfd5d.png)

**Comment by jiffyette** [comment]
this has already come up, its a low priority

**Comment by DaantjuhNL** [comment]
Well that mentions levels, this item is completely useless
