### ISSUE TITLE
Alliance

### ISSUE THREAD

**Issue by Ryddag** [ProjectCeleste/Celeste_Server#12]
Not implemented yet.

**Comment by onlinemindgem** [comment]
Info: When I get Delian stuff I can't equip. Got an Imhotep item which I could equip. So guess that is default or the check ingame is missing for this alliance

**Comment by deefbert** [comment]
That's odd - I couldn't equip an Imhotep item.

**Comment by CharlieTheMcPro** [comment]
Maybe the game randomly auto selects alliances for you so mindgem might be Council of Imhotep and deefbert you could be delian league or Legion of Carthage

**Comment by Ryddag** [comment]
Quest and stuff implemented on last update
