### ISSUE TITLE
quest hardness

### ISSUE THREAD

**Issue by jiffyette** [ProjectCeleste/Celeste_Server#122]
i honestly think that some of these quests are impossibly difficult on elite / leg

yes leg you complete me is meant to be co op. but doing it solo can the hardness of the ai be reduced ? i got sieged to death, solo impossible. also some of the 12k recaptures - are harder than say leg paphos. in my opinion :)

**Comment by Ryddag** [comment]
I close this because is not an issue but more an suggestion, repost this on your website when it will be online (i hope soon).
