### ISSUE TITLE
Blueprint - Small Norse Residence

### ISSUE THREAD

**Issue by BOSAIF86** [ProjectCeleste/Celeste_Server#128]
Hello, 

I got "Small Norse Residence" Blueprint while questing, whenever I try to use it, it opens up a "PRO NORSE CIVILIZATION PACK" buy menu! please check the image below:

http://imgur.com/VUR50JR

**Comment by Ryddag** [comment]
Its not a bug ^^ those item can be build only for those who own the associated pro civ, you will can build it when norse will be unlocked
