### ISSUE TITLE
Produce with craftshop and school

### ISSUE THREAD

**Issue by Ryddag** [ProjectCeleste/Celeste_Server#129]
You can learn any school and build any craftshop, but can't produce yet.

**Comment by ChewierElf** [comment]
Hi.
I tried several normal workshops. Farmer, Smelter, Logger, Mason.
I can NOT build as of yet. Maybe ?? because I am a regular player? Not a tester or supporter?
Tested as of 30 min before posting this.
Recipies learning is not an issue for me.

**Comment by Semperfi0817** [comment]
When you say you can build any craftshop do you mean you can place a blueprint and create that building? If that is what you mean then I can confirm I cannot. I can right click and the building appears but when trying to place anywhere, nothing happens. I have tried on both Greek and Egypt civs.

**Comment by Ryddag** [comment]
@ChewierElf #4
