### ISSUE TITLE
Undo Sell

### ISSUE THREAD

**Issue by Ryddag** [ProjectCeleste/Celeste_Server#13]
Not implemented yet.

**Comment by onlinemindgem** [comment]
just adding some info as what is mentioned here: At selling the items should move to the shop box and button to undo should light up

**Comment by M3SUT85** [comment]
Sorry didn't notice this thread was open already. Glad there is a way of confirmation, I will sell that way from now on. Thanks.

**Comment by M3SUT85** [comment]
An update on this, I tried doing left click and placing item into store, it doesn't work for me.
