### ISSUE TITLE
Capital Cosmetics Unavailable

### ISSUE THREAD

**Issue by IAsAbovesoBelowI** [ProjectCeleste/Celeste_Server#130]
Cosmetics such as the ones used in AI Capitals are unavailable.
   _-Walls_
Cosmetics such as Units are unavailable.
  _-RTS gear upgraded cosmetic changed Units are unavailable._
Cosmetics such as Buildings from RTS maps.
  _-RTS gear upgraded cosmetic changed Buildings are unavailable._

**Comment by Ryddag** [comment]
#131

also "Cosmetics such as Units are unavailable" look vanity island their a few units and building peaceable in capital to sell
