### ISSUE TITLE
Some issues with the new "1v1 ranked match" in Sparta

### ISSUE THREAD

**Issue by WiriWout** [ProjectCeleste/Celeste_Server#133]
- After killing every single unit from the enemy, the quest is still not completed. 
- The costs of certain upgrades are not champion mode. For instance, going to age 3 as greeks costs 400 wood/gold/food, whilst in champion mode this is 300 wood/gold/food
- Even when starting the quest as egypt, you will play as greeks
- There's a weird bug with the idle villager icon appearing when no villagers are actually idle. Pressing the button/hotkey does not do anything, since there are no idle villagers.
- A pretty severe villager bug: Villagers that finished building a storehouse/dock/town center will not start gathering the most nearby resource after completing the building. Instead they will go idle. This does however work when building a farm; the villager starts gathering food.
- It's possible to use consumables, which were disabled in the original champion mode
- Advisors are enabled in the quest, which were not available in champion mode.
- The upgrades for the fishing ship and the merchant transport were missing (for Greek).
- There's also a bug where any unit that can attack will be weirdly aggressive when you order it to move away. Instead of moving, the unit will attack, almost as if the attack move command was used.
- There appears to be a bug with rally points for the town center. Villagers that were rallied to a tree did not end up gathering wood.

**Comment by WiriWout** [comment]
I'll add some more issues to the first post as we find more.

**Comment by Ryddag** [comment]
Can check the today update, and tell us what still need to be fixed, thx.

**Comment by francot514** [comment]
I can confirm quest is not completed by destroying Town Center before killing units.

**Comment by Ryddag** [comment]
quest removed since now we have arena
