### ISSUE TITLE
learicorn

### ISSUE THREAD

**Issue by jiffyette** [ProjectCeleste/Celeste_Server#137]
before the loot table was changed learicorn was super rare. ive now seen 7 of them in game in persian civ, while levelling from 20-29. its not rare anymore its common ! 

can this be changed please. id much prefer proper treausre chests, than learicorns !

**Comment by musictopia** [comment]
I agree with that.  Do you think that designs and blueprints show up too much?  The good news is I can edit the loot tables.  However, I can't count on whether it will get approved though.

**Comment by jiffyette** [comment]
i think the learicorn shows up far too often. i also think the drop rate for legends is too high =- ive seen people doiong alliances and getting triple legends - legends are supposed to be rare !

**Comment by musictopia** [comment]
The reason people are getting legendary gear from alliance quests is if they get 100 percent, then the last optional challenge are from the legendary loot tables.

**Comment by jiffyette** [comment]
that makes sense :D

**Comment by Ryddag** [comment]
learicorn is only available on certain at certain lvl only, but i agree seem to pop to much
