### ISSUE TITLE
Lericorn Statue can't be deleted

### ISSUE THREAD

**Issue by Wobling** [ProjectCeleste/Celeste_Server#140]
Have multiple, can't be sold or deleted.

**Comment by jiffyette** [comment]
build them then, and dont pick them up. its not meant to be deletable. in the original game they were extremely rare, if u found one you was special !

**Comment by Wobling** [comment]
@jiffyette the problem is that they're not rare at the moment, I've found 3 in 4 missions. This isn't intended so while they fill my bags is a waste of space.

I also don't have the materials to make them. Making them deletable or sellable is an alternative measure to fix this issue.

**Comment by Ryddag** [comment]
Now they are destroyable, and leriacorn will appear less.
If you want i remove them from your inventory mp me (item gain before update are still un-destroyable)
