### ISSUE TITLE
locking legends to where they originated from

### ISSUE THREAD

**Issue by jiffyette** [ProjectCeleste/Celeste_Server#147]
so at the moment when we get a chest drop on elite or legend we can get legendary items. 

on the original game you could only get arrow of acteon from cypress store, in celeste you can get in a chest drop. is there a way of locking said items in said stores ? if i wanted arrows of act, id buy from cypress store, id much prefer a lens of menes  as a example. any plans to make the items appear in the original places as they were in the original game ?

TY

**Comment by DaantjuhNL** [comment]
I actually like to be able to get every legendary from a chest

**Comment by jiffyette** [comment]
im happy it works for y ou, maybe a community poll on the topic

**Comment by Drazerino** [comment]
and make more rare the leg items

**Comment by jiffyette** [comment]
no point having all orange, ( legend) a lot of epic / rare items are actually much better than most of the legendary gear

**Comment by Drazerino** [comment]
they gona fix leg item, must be better than rare or epic....  microsoft just fail balance the stats of items

**Comment by jiffyette** [comment]
wont happen ^^ breaks the game

**Comment by onlinemindgem** [comment]
Also locking the Alliance items to only be able to buy
