### ISSUE TITLE
GUI - Add Empire Points

### ISSUE THREAD

**Issue by BOSAIF86** [ProjectCeleste/Celeste_Server#149]
The "Add Empire Points" button at the top toolbar does not work. (used to be working in previous patches I believe!)

**Comment by musictopia** [comment]
I would suggest allowing somebody to purchase empire points with coin.

**Comment by Ryddag** [comment]
I disabled it, since we will NEVER sell EP!

**Comment by BOSAIF86** [comment]
How can we buy stuff from EP store then? are you guys planning to change the currency?
