### ISSUE TITLE
Repeatable quests has problems if you accept but don't complete before logging off

### ISSUE THREAD

**Issue by musictopia** [ProjectCeleste/Celeste_Server#15]
In capital city, if you accept quest and log off, then when you log on, the blue exclamation point still appears and if you do the quest, it gets hosed so it would never show as completed.  The only temporary workaround for now is to abandon the quest and accept again.

**Comment by Ryddag** [comment]
I need more info, witch quest exactly ?

**Comment by Ryddag** [comment]
I tried to reproduce this bug, without success but in current dev build, so maybe other fix as also fixed this one or maybe its only for some quest (Timer?)

**Comment by Ryddag** [comment]
Fix will be deployed on next server update.
