### ISSUE TITLE
elite meet in crete is too hard

### ISSUE THREAD

**Issue by jiffyette** [ProjectCeleste/Celeste_Server#150]
i used to play elite meet in crete in the old game, this new one on celeste is impossible, survived to wave 37 then died on greek. siege waves never kept going from 31 - 40 in original. celeste they do , u cant bounce back from constant siege.  im assuming its tier 4 ? 

also u dont start with enough towers like u did in the original. please dial the ai toughness back a little please ?

also one other thing, while going from waves 11 - 20 i found the ai very easy . so maybe its just out of balance ?

ty

**Comment by MrPSIHO13** [comment]
i cant go pass wave 37 - 2 hard 4 me :)
like jiffy say after wave 30 is brutal hard

**Comment by musictopia** [comment]
I would agree that they should tone back the elite meet in crete.

**Comment by Ryddag** [comment]
elite meet in crete don't use tier lvl like normal Crete quest. It's untouched, we have changed nothing in this one.

**Comment by jiffyette** [comment]
weird, coz its monumentally harder than it was when the game got shut down

**Comment by MrPSIHO13** [comment]
ok will try again with some empire powers and see if its possible

**Comment by musictopia** [comment]
If its harder now, then its probably because there are no milestones.   Plus players may not have the max gear required.  Also, maybe there are advisors that help that players can't get as easily like the ones from skirmish.

**Comment by jiffyette** [comment]
its harder because the ai sieges non stop from 31 to 40, it didnt in the original, check youtube

**Comment by musictopia** [comment]
jiffy, did you play as greeks?  Because on project penelope where I have the code, they actually increase the hit points of the siege quite a bit on the original if the greeks use too many palins.

**Comment by jiffyette** [comment]
i did use greeks - hippies and towers to be exact. mr p did it with egg , but he used a crap ton of consumables

**Comment by MrPSIHO13** [comment]
not hard anymore :D

**Comment by jiffyette** [comment]
u cneated

**Comment by Ryddag** [comment]
coop will make it easier now
