### ISSUE TITLE
Nonreacting enemy

### ISSUE THREAD

**Issue by Monsters97** [ProjectCeleste/Celeste_Server#154]
One of the 2 enemies in: We killed these guys is not doing anything.

**Comment by musictopia** [comment]
I would not consider this a bug.  This would actually be a good thing because otherwise, it makes the quest too hard.  I think its fine as is.

**Comment by jiffyette** [comment]
the ai does the same thiung in "you complete me"

**Comment by musictopia** [comment]
i completed the quest and ai worked properly.

**Comment by Ryddag** [comment]
ok so i close thx
