### ISSUE TITLE
Testing: No Argos on babylonians

### ISSUE THREAD

**Issue by onlinemindgem** [ProjectCeleste/Celeste_Server#157]
Started testing babylonians. I see no Argos on them, while the should. See the YouTube below. Just can see on the quest window the Argos region and the quest It burns us.

https://youtu.be/2QqIObaG1CE?t=1m2s

**Comment by musictopia** [comment]
Why would babylonians be tested when the celtics are not even out yet?

**Comment by onlinemindgem** [comment]
To keep things rolling for the future

**Comment by Ryddag** [comment]
on my last their appear just after i accept first quest in cap city, quest get you a new one who tell you to go argos, can you recheck ?

**Comment by onlinemindgem** [comment]
Persians I can confirm to have Argos, but still no Argos on babies or norse.

**Comment by onlinemindgem** [comment]
Now I can access argos before level 20.

According to kevsoft and I think is right:

_mhh, as far as I know it should be only unlocked when you read lvl 20



actually: you get a quest unlocked at lvl 20, which grants you access to argos afterwards



I know that this is true for greeks and egypts_

**Comment by Ryddag** [comment]
Normally all is fixed about this now
