### ISSUE TITLE
Coop : User in same LAN

### ISSUE THREAD

**Issue by matt60400** [ProjectCeleste/Celeste_Server#159]
Hi,

I have a problem when i play in coop with a secnod player in same lan its doesnt work even with  VPN.
andIf I want to play with an other player I am forced to open port 1000-1005.

**Comment by luciano7** [comment]
@matt60400 can we close this?

**Comment by matt60400** [comment]
its work but i should disable firewall windows ....

**Comment by Toetje585** [comment]
Never disable windows firewall,  just allow the game trough the firewall on both machines and or open ports 1000 to 1005 in Windows firewall.
