### ISSUE TITLE
Crafting Materials Not Producing / Cannot build more than 2 of each workshops.

### ISSUE THREAD

**Issue by doddianca** [ProjectCeleste/Celeste_Server#165]
My workshops have worked all night and nothing shows up for being 'made' in quantity area.  Also, if logged out is the materials still supposed to be produced, the count downs seem to be restarted when I logged in today.  Also previously you could build as many of the same type of shop, now only allows 2.

**Comment by Ryddag** [comment]
Advanced workshop is limited to 2, standard to 8.
If you check path note note, you will see its not implemented yet (last update only allow to run prod nothing more)
