### ISSUE TITLE
QUEST: Egypt-Lybia: Not to be triffled with. Only ELITE enemy.

### ISSUE THREAD

**Issue by ChewierElf** [ProjectCeleste/Celeste_Server#167]
Playing this quest the AI only spawns Elite Desert swordsmen and Elite Desert Cavalry men. The villagers are normal. Also nothing gets built by the AI.
The quest is available around level 15 when I played it when I was already level 20. Not sure if that is taken into account by the AI and therefore scales up with the level of the enemy. I heard some other players mentioning this behavior as well.
Will try to play the quest again in the future at a more appropriate city level and give feedback.
Perhaps lower level testers can confirm or deny this Elite behavior for a quest supposed to be around level 15.

**Comment by DaantjuhNL** [comment]
I played it once I was 40, but yes all enemies were elite (villagers are never elite)

**Comment by musictopia** [comment]
I can honestly say that even the original version, they were all elite units.

**Comment by ChewierElf** [comment]
Alright. Seems that it is a fact that Musictopia honestly knows that this was in the original as well.
So it is by design, by default. Just thought it to be weird that at level 15 a player only gets Elite soldiers to deal with. Guess this can be closed. No further action needed. My bad.
