### ISSUE TITLE
No enemy town center in pirates when coop

### ISSUE THREAD

**Issue by musictopia** [ProjectCeleste/Celeste_Server#168]
I tried 3 times for the first pirates quest where you have to destroy the enemy town center.  It showed no town center so even if the enemy is defeated, you still cannot win the quest solo.  I tried solo and it did show the town center.

**Comment by Ryddag** [comment]
Still append?

**Comment by jiffyette** [comment]
in co op the enemys town centre on the first island isnt there, u cant complete it, solo yes u can

**Comment by KevinW1998** [comment]
yea, I can confirm this. Just played with my mate and there was no town center

**Comment by Ryddag** [comment]
What the name of this quest ?

**Comment by musictopia** [comment]
The quest name was Take That! Tamiat Pirates!

**Comment by cad39again** [comment]
working on it
