### ISSUE TITLE
does nerfd stat items exist ?

### ISSUE THREAD

**Issue by jiffyette** [ProjectCeleste/Celeste_Server#169]
i have been called a lier , a scammer and a cheat repeatedly, i do not check stats. i list the item and send it, if its nerfd its not my fault.

does nerfd stats exist ryddag ? as far as im aware they dont.  please clear this up. i hate having my gaming experience made so hateful towards me because i dont check stats

**Comment by Drazerino** [comment]
trush scammer gtfo

**Comment by jiffyette** [comment]
what ? admin has made a anny nerfd stat doesnt exist

**Comment by Ryddag** [comment]
like i said no.
