### ISSUE TITLE
Bug with the item´s stats 

### ISSUE THREAD

**Issue by Cokersaturno** [ProjectCeleste/Celeste_Server#171]
Hi everyone.Today when an user sent me an item,the item´s stats was nerfed.The gear was council wall that had 86,7% health on the chat but when he sent me the item had 84,3%health on the email so i decided bought it  because the item was cheap and when i bought it the item´s stats  returned to normal.This bug caused problems between 2 users.

**Comment by Ryddag** [comment]
look announcement in discord.

@everyone Gear can't have nerfed or buffed stats, an item at level 40 for example will always the same stats! When you buy always check the item in mail, and if not the good one you just have to decline it.(édité)
