### ISSUE TITLE
We Need A Force Too Hard

### ISSUE THREAD

**Issue by musictopia** [ProjectCeleste/Celeste_Server#172]
Ever since the patch was released where a player had to be in age 4 in order to build the 4th town center, it made the quest not possible to beat because a player has to go to age 4 in order to build the 4th town center.  In the original game, the player can at least use the resources of the empires.  However, here a player had to be in age 3 in order to do so.

**Comment by jiffyette** [comment]
actually it is possible my friend, i have done it, no consumables, u make hysapists.

**Comment by Ryddag** [comment]
not an issue
