### ISSUE TITLE
Legendary: A new Rebellion Broken as can be coop

### ISSUE THREAD

**Issue by DaantjuhNL** [ProjectCeleste/Celeste_Server#173]
RiskeyVM(hansolo) and I wanted to try if we could beat the quest, but when we launched it coop, the coop partner was, elite, the enemy and couldn't move. Furthermore he could see the whole map, restarting or lauching didn't help. So this quest needs some work

**Comment by jiffyette** [comment]
this needs to be fixed, works solo but not co op

**Comment by Ryddag** [comment]
Can you tell me if with last update i properly fix this ?

**Comment by jiffyette** [comment]
last updaate didnt, still bugged on elite mode enemy ai with co op

**Comment by jiffyette** [comment]
definately bugged, your co op partner is ellite glowing red, and cant move
