### ISSUE TITLE
Being able to play coop seems 50/50

### ISSUE THREAD

**Issue by DaantjuhNL** [ProjectCeleste/Celeste_Server#174]
I can play with some people fine, some with a bit of lagg, and with some not at all, it goes in an infinite loading while saying "game disconnect". I dont know what causes this, so I dont know how to report it, but that's the issue I have 50/50 on coop

**Comment by Ryddag** [comment]
Like we said coop is p2p that why you can play with some user and some not. Try to ping you each other to see if you have a good connection between you.
