### ISSUE TITLE
Alliance materials Not turning in

### ISSUE THREAD

**Issue by doddianca** [ProjectCeleste/Celeste_Server#175]
When completing an alliance materials, you try to turn in the materials nothing happens, giver still has a question mark above him.

Update: Had tried this about 5 times to complete it nothing, then all of sudden it worked maybe faulty will have to try again or someone verify thanks.

So I think the issue here is if the materials are not in ONE stack they do not allow them to be completed.  This is the issue now I think with the Ambrosia Project.

**Comment by Ryddag** [comment]
Server check you really have thoose mat, and actually you are ritgh they need to be in same stack, i will work on this
