### ISSUE TITLE
Ambrosia Project NOT Allowing Complete

### ISSUE THREAD

**Issue by doddianca** [ProjectCeleste/Celeste_Server#176]
So tried to hand in Ambrosia Project will not accept it, have 14 spaces of the warehouse filled with the items.  Exited game and re-entered to see if that would trigger it, it did not work.  The actual quests within the project do allow them to be turned in.

**Comment by musictopia** [comment]
I've completed the ambrosia project many times with no problem.  I doubt anything with the new update would break the ambrosia project.

**Comment by doddianca** [comment]
I do the project on two civs every day twice a day.  So now you have stacked the items of the same type before allowing it to complete, however, do not cash it in.   You now need to complete the quests before the ambrosia project or you will have fulfilled the quest except the fact you don't have the reward item for it.  So it's now in limbo.  
![alpine escort](https://user-images.githubusercontent.com/29316464/27944855-8155cb6e-62b7-11e7-996a-6ef91a91b51c.jpg)

**Comment by Ryddag** [comment]
Last update seem to have fixed it.
