### ISSUE TITLE
loot tables are too bad

### ISSUE THREAD

**Issue by jiffyette** [ProjectCeleste/Celeste_Server#178]
before patch , legends dropped too often. now they dont drop at all

ive done 12 alliance quests, got 9 epic advisors, 2 sacks of coins, 2 golden tickets, no epic items, no legends, please fix !

**Comment by onlinemindgem** [comment]
Since patch it seems no gear drops at all!

**Comment by jiffyette** [comment]
thats right - i just did leg breaking badits -0 thinking id at least get a epic - 3 epic advisors nothing else, its been tweaked the wrong way :(

**Comment by KevinW1998** [comment]
It is intention that the drop rate for leg items hat been reduced. However, we didn't change the chance of the item types. This is probably a bug.

**Comment by jiffyette** [comment]
major bug. i dont mind getting epic councilman, i do mind getting trash , like boxes of cats on leg quest

**Comment by musictopia** [comment]
I think its possible that when introducing the variable statistics on gear, that caused a bug so instead of getting a runtime error when opening the chests, it will just choose another random one so gear would never be chosen.

**Comment by MrPSIHO13** [comment]
today drop are only advisors,mats,recepies,blueprints,etc...
100% no gear drop

**Comment by jiffyette** [comment]
was it intentional to bring back los ?

**Comment by musictopia** [comment]
I hope it was intentional to have line of sight because that is very important on quests.

**Comment by jiffyette** [comment]
except  will it mean non los items worth more ? 📦

**Comment by musictopia** [comment]
No, the non line of sight items would not be worth as much because line of sight is always valuable.  What would happen is the old items without line of sight would not be worth as much.  That would be fine though.  If that part would remain, then eventually, there would not be too many old items left as players use the line of sight version instead.

**Comment by jiffyette** [comment]
problem is markets flooded, and nothings of value right now, or its coz not enough player base

**Comment by jiffyette** [comment]
i like it how microsoft did it , los, then phase out los, pushing los up
