### ISSUE TITLE
Helen has been taken bug.

### ISSUE THREAD

**Issue by Goregie** [ProjectCeleste/Celeste_Server#180]
When trying to turn it in it doesnt give me credit. Its just like the milestones were it lets you hit the complete button but doesnt let you continue on the quest chain.

**Comment by musictopia** [comment]
i completed it a few weeks ago with no problem.  unless a new bug was introduced.

**Comment by Ryddag** [comment]
If some one can recheck this

**Comment by Goregie** [comment]
Managed to find a "fix" to it. you need to have them in 1 stack of 100 and not 5 stacks of 20.

**Comment by jjur** [comment]
He means, there is a quest, where you have to get some materials (for example 100 pine planks). When you have one type of material in 2 or more stacks (Inventory: 20xPine Planks, 60xPine Planks, 20xPine Planks), complete button only closes window, but quest remain unfinished.
I saw this bug at in: "I Have a Cunning Plan" quest (http://ageofempiresonline.wikia.com/wiki/I_Have_a_Cunning_Plan)
