### ISSUE TITLE
Certain consumables are used multiple times when clicked

### ISSUE THREAD

**Issue by Wobling** [ProjectCeleste/Celeste_Server#182]
Labour of the empire, I had a stack of 5 used one and it ticked down and consumed all 5 but only gave me the villagers once.

**Comment by musictopia** [comment]
It looks like it may be just certain ones.  I tried armanda of the empire.  I had a stack of 2.  I used one and it did correctly reduced by one.  Also, I tried purchasing in argos 5 of the spy glasses.  Stacked them.  Used one of them and it still correctly reduced by one.  I don't feel like spending empire points to give more details about this.

**Comment by Wobling** [comment]
Happened to a 3 stack of siege.

**Comment by Wobling** [comment]
To add to this, I've noticed sometimes a random number of that stack will reappear in my inventory and then if I use it it counts down and uses them all again.

**Comment by jjur** [comment]
The same at Priests of Empire and Woodcutting Elephants

**Comment by M3SUT85** [comment]
What is happening about this bug? Many times I have also brought it to the devs attention, nothing concrete is said or done about it. ??

**Comment by M3SUT85** [comment]
To add, it happens with empire consumables that spawn from Town Centre only.

**Comment by Ryddag** [comment]
we use those consumable you click one time and wait, or spam click ?

**Comment by jjur** [comment]
After click one time it gradually decreases. For example: 5x consumables -> click -> 1x spawn at TC and 4x remains -> 1 second -> 3x remains -> 1 second -> 2x remains in inventory.
It occurs always with Empire consumables and for me also with Mycenae Archers.
It can be alternatively solved by triple Empire consumables pack (5 -> 15).

**Comment by M3SUT85** [comment]
It happens with anything that spawns from Town Centre I think. It happened to me with rogue priests and bandit cavalry.

**Comment by M3SUT85** [comment]
I click once, it takes whatever is in the stack, whetehr it be 2-3 or 5. One time click takes all stack.

**Comment by jlquincy** [comment]
I have used labor of the empire and army of the empire without a hitch.

**Comment by jiffyette** [comment]
those consumables dont bug - resources of the empire does, uses 2 every hit

**Comment by M3SUT85** [comment]
Found a temporary fix for this issue although it may be inconvenient for some people, you can now split the stack and have singles, therefore it will only use once.

**Comment by musictopia** [comment]
The splits don't work with consumables that require empire points.  Already tried that workaround.  That only works for items that are tradable.

**Comment by musictopia** [comment]
The unusual thing is when I used the wolves on some coop only quests, it used up more than one immediately but used the same thing on skirmish and does not have the problem.

**Comment by Harrikrishna1** [comment]
same today when i playing legentary marion i used priest of the empire 1 time and i lost 2 pieces need to be fixed soon in upcoming updates.
