### ISSUE TITLE
On high DPI screen UI is screwed up

### ISSUE THREAD

**Issue by artisticcheese** [ProjectCeleste/Celeste_Server#186]
Mouse position does not correspond to actual position of active region.

**Comment by Ryddag** [comment]
This is game issue we can do anything, we can't change the game.

**Comment by artisticcheese** [comment]
Solution for anybody with the same issue is to have following checkbox checked on `Compatibility` screen
![image](https://user-images.githubusercontent.com/13176884/27986006-af2e234a-63bd-11e7-942b-3b980c30fd95.png)
