### ISSUE TITLE
Selling epic items shows selling for 0 coins

### ISSUE THREAD

**Issue by musictopia** [ProjectCeleste/Celeste_Server#19]

**Comment by Ryddag** [comment]
Witch epic items, i have a few of them they have price.

**Comment by musictopia** [comment]
Actually, I figured out a pattern.  The issue is not just epic.  If somebody equips and item, then it shows the selling price of 0.  However, in the original game, even if they equipped it, they can still sell to the store.  They just can't trade.

**Comment by Ryddag** [comment]
Ok i will fix this
