### ISSUE TITLE
Palace Run Coop Crash

### ISSUE THREAD

**Issue by Wobling** [ProjectCeleste/Celeste_Server#191]
The non host participant will load the quest then get reloaded into his home city. The Host can play but is made aware the coop partner disconnected.

Happened on Both Crete and Egypt Palace Runs.

**Comment by Ryddag** [comment]
If someone can test this

**Comment by SubZero787** [comment]
Yes, so for allianxe quests: palace race belgica,crete,egypt. When the host starts the quest, he can still play but his partner cannot. I found a fix for this. First start the quest, then while you're in the quest( i mean don't log out), promote your partner and then let him start the quest from the SAME alliance(Delos for example) it should work just fine.

**Comment by Ryddag** [comment]
I confirm SubZero787  work arround, promote seem to fix it idk why
