### ISSUE TITLE
Argus Starting Quest

### ISSUE THREAD

**Issue by atum123** [ProjectCeleste/Celeste_Server#193]
Picked up "Emissary to Argos" (http://ageofempiresonline.wikia.com/wiki/Emissary_to_Argos).
Logged off for the day and wanted to turn it in the day after.
Couldn't turn in "Emissary to Argos" at the "Argos Captain" in Argos.
Tried to cancel the quest to retake and complete it.
Quest isnt avilable anymore.
My friend has exactly the same issue, but he didnt cancel it, just can't complete it in.

Would be nice if you could look into it, maybe if you dont complete it right after getting it it's bugged.
Also if this quest can be retaken after canceling.

Maybe related to our level, since we're not level 20 yet but had the quest already, somehow.

**Comment by musictopia** [comment]
I had no problems with this starting quest.  If you had the problem because you decided to close out instead of completing the simple parts, then not sure if that can even be fixed.

**Comment by atum123** [comment]
Thanks for your answer but you didn't read:

> My friend has exactly the same issue, but he didnt cancel it, just can't complete it in.

**Comment by Ryddag** [comment]
you will get back at lvl 20, its was an issue you get it sooner
