### ISSUE TITLE
6-warehouse-bug

### ISSUE THREAD

**Issue by tj200** [ProjectCeleste/Celeste_Server#194]
got 6 warehouses and the 12-slot warehouse can't be unpacked (empty).
![6warehouse](https://user-images.githubusercontent.com/30055947/28034884-dcb8943e-65b2-11e7-8bd9-8c4570dccbfd.jpg)

**Comment by Ryddag** [comment]
I checked your save this warehouse seem gone, i don't see any of your civ with more than 5 of them
