### ISSUE TITLE
Babylon Quests

### ISSUE THREAD

**Issue by thek33** [ProjectCeleste/Celeste_Server#198]
Hello,
I'm unable to validate finished quests from Babylon. NPC don't have the exclamation point.
I tried to cancel one that i finished but can't take it again, it's like the quests don't exist anymore.
NPC is present, it's Engineer Farzana from what i remember.

Quests are (sorry, i don't remember the last i canceled):

Alpine Escort
Loot Island of king Tusk
Don't cry for me Farzana
Temple of the loom

**Comment by doddianca** [comment]
If you completed the whole Ambrosia Project, and handed it in prior to the individual quests they will be in limbo.  If you have materials in your storage that did not go over to the engineer you "may" have had to stack the umbrellas and honey.   I just completed these quests and had no issues doing the rewards along the way for individual quests, then hand in the completed Ambrosia one.

**Comment by Ryddag** [comment]
same has #193
