### ISSUE TITLE
Celtic Tech Tree

### ISSUE THREAD

**Issue by Semperfi0817** [ProjectCeleste/Celeste_Server#199]
I believe the tree is incomplete for Celtic Civ. Tower and wall only has 1 upgrade available. I could be wrong but I believe every Civ offered 2 upgrades. additionally the screen for tech upgrades  does not show the lines for progression on every TAB.

**Comment by musictopia** [comment]
i can tell you the original game, the celtics only had one wall upgrade which was for age 2.  Therefore, there is no bug here.

**Comment by Semperfi0817** [comment]
Thanks M. Been a long time since we could play this lol. Glad someone remembered.
