### ISSUE TITLE
Northern Hold: city defenses slightly bugged

### ISSUE THREAD

**Issue by DaantjuhNL** [ProjectCeleste/Celeste_Server#201]
In the Northern Hold booster pack you eventually get overarching missions to defend every city in coop, lose no victory towers, win with a 30 point lead etc. So I did sens, crete and argos today in coop (Pharos) without losing victory towers. Only sens counted towards the progress of doing defenses in coop and not losing victory towers. We also won Argos with 60 vs 28, a 30 point lead, this quest was also not completed. Seems these overarching quests needs some finishing touches

**Comment by jiffyette** [comment]
can confirm this, the bonus things arent accepted or observed by the game

**Comment by musictopia** [comment]
Actually, the global quests for 30 point lead, etc, is for city conquest, not city defense quests.

**Comment by lukipr0** [comment]
what musictopia said. you just have to distinguish between city conquest and city defense. basically if your hero is vemundr, it counts towards these quests.

**Comment by Ryddag** [comment]
So its an issue or not really (not i have fully understand) ?

**Comment by DaantjuhNL** [comment]
It's my fault I confused city defenses with conquests

**Comment by Ryddag** [comment]
ok so i can close :)
