### ISSUE TITLE
Quest:Beat the Barbarians!

### ISSUE THREAD

**Issue by MrPSIHO13** [ProjectCeleste/Celeste_Server#202]
one of 1st quests for celts
- ai villagers idle
- ai not making army

**Comment by someNub** [comment]
This also happens in other missions involving friendly ai.
However after restarting those missions in about 1 of 100 times they seem to do something.

**Comment by Ryddag** [comment]
i assume it the 3 or 4 quest of tutorial ? if its like this.

**Comment by musictopia** [comment]
I think that quest is fine as is because its a tutorial quest.
