### ISSUE TITLE
Unobtainable Gear

### ISSUE THREAD

**Issue by someNub** [ProjectCeleste/Celeste_Server#203]
Some items seem to have additional "line of sight" on them due to some bug in earlier stages of the game. New items don't have it anymore.

This should be removed on (the older version of) those items (also already equipped ones) or added back into the game.

Reasons: 
Unobtainable statted gear shouldn't exist in a multiplayer game.
Extremely unfair advantage in geared (not champion) pvp matches to be able to use unobtainable gear.
Also a little bit unfair in pve.
Annoying for people who havent been able to play the game before the removel of the stats, due to a lack of time or having no key yet.

Edit: It may have been the same problem in the original AoE online. They had many flaws, and this was one of them.

**Comment by Ryddag** [comment]
It was same in original game when those item were changed, old user still have them. Like collector item (mummy bandage or norse pole lvl40 for example).

**Comment by someNub** [comment]
Seems rather unfair
