### ISSUE TITLE
Coop within a LAN

### ISSUE THREAD

**Issue by fabsroman** [ProjectCeleste/Celeste_Server#205]
I've tried several things, and none of them have worked. I forwarded ports udp/tcp 1000-1005, 1500-1510, and 900 on my computer, restarted the router, and it does not work. I tried changing the laptop from one wireless router to another, and it still does not work, Tried using one desktop with my desktop, and it did not work. Tried using a laptop with my desktop, still did not work.

The only way I was able to coop with my kids is to put a laptop on a hot spot using my phone. Then, the coop actually worked. Any advice would be appreciated.

**Comment by KevinW1998** [comment]
As long as you only play coop or 1v1 pvp, you can set the launcher into "LAN"-Mode:
![image](https://user-images.githubusercontent.com/4018533/28200778-4a2f5224-686e-11e7-80f0-7616b2008d6a.png)

and then:
![image](https://user-images.githubusercontent.com/4018533/28200805-5f6de592-686e-11e7-8797-e74358a9441f.png)
for both computers.

**Comment by Toetje585** [comment]
Did you also forward them in your router? 1000-1005 UDP is needed if you like to coop over WAN. And they need to be open for all ipv4 adresses you like to play on. However the above posted by Kevin works aswell if you only like to play on your LAN network.

**Comment by fabsroman** [comment]
Seems as though making the LAN selection works. Just finished my first coop with my 8 year old son without having to use a hot spot on the laptop. He is so excited. Thanks to both of you for the help.
