### ISSUE TITLE
Coop bug

### ISSUE THREAD

**Issue by MrPSIHO13** [ProjectCeleste/Celeste_Server#210]
cant play crete  and some alliance (palace race) with friends 

- when leave party chat server wont work sometimes or even quest map - need relog to work again
- sometimes coop quest from alliance wont count

**Comment by jiffyette** [comment]
we found this too, elite meet in crete, my partner is automatically kicked from game, although im in the game, hes kicked back to his capitol

**Comment by Ryddag** [comment]
#191
