### ISSUE TITLE
Guardian Rewards Random Number of Chests

### ISSUE THREAD

**Issue by doddianca** [ProjectCeleste/Celeste_Server#211]
The original version the game had randomly generated chest rewards per guarded chests.

Small Campfire 1 chest was obtained
Medium Hut 1 to 2 chests could be obtained
Large Tent 1 to 3 chests could be obtained

Any way to look into this, as some quests are pretty difficult to get to a large tent only to have one reward of a "box of cats".

**Comment by atum123** [comment]
#116
