### ISSUE TITLE
crete issues

### ISSUE THREAD

**Issue by jiffyette** [ProjectCeleste/Celeste_Server#212]
jole and i , were trying to play the crete leg missions in co op.

1) 9 times out of 10 the game kicked one of us back to the capitol city , and the game automatically failed. we relogged multiple times, change leaders and it stil did it.

2) we tried the leg quests and got wiped at wave 5. we tried the non leg ones on elite, and got wiped at wave 10. me greek jole egg. either we complettely suck ( we have successfully done all other leg quests together)  or the hardness setting is too hard. i cannot remember these being to hard. 

PLEASE FIX THE CRETE HARDNESS AND KICK / BUG

ty

**Comment by Ryddag** [comment]
1. #191

2. Leg and elite version don't exist at all in original game
