### ISSUE TITLE
Alpine Escort

### ISSUE THREAD

**Issue by jlquincy** [ProjectCeleste/Celeste_Server#213]
My user name in the game is SoCalDeerSlayer. I completed the Alpine Escort quest but am unable to redeem it. I have searched all over the quest city and clicked every question mark I am able to see but it is not there.

**Comment by musictopia** [comment]
I completed the quest several times with no problems.

**Comment by jlquincy** [comment]
It would be great if I could simply abandon it. Would you do the quest again then send me a screenshot of the quest location where you turn it in?

**Comment by Ryddag** [comment]
due to an old bug where the quest was unlocked too soon abandon it, it will reaper later.

**Comment by Sayfron** [comment]
jlquincy 

Hello I also have the same problem that I have the items in the bag but unfortunately can not give
