### ISSUE TITLE
Library d3dx9_40.dll not found

### ISSUE THREAD

**Issue by danigonlinea** [ProjectCeleste/Celeste_Server#216]
I have installed the game from scratch, after it I have applied last update (v136) and I get error d3dx9_40.dll is not found.

How can I solve this issue?

**Comment by lukipr0** [comment]
it's right there in the error name: dx9.
so i suggest this: [http://nauticalgames.eu/files/directx_directplay_guide.pdf](url)

**Comment by danigonlinea** [comment]
Yes, you are right.

Here's the fix by the way.
http://www.microsoft.com/en-us/download/details.aspx?id=35
