### ISSUE TITLE
Bug With Up For A Bit Of Fishing And Ready To Build Some Farms

### ISSUE THREAD

**Issue by musictopia** [ProjectCeleste/Celeste_Server#218]
On my celtics, I chose the option to skip tutorial.  However, those 2 quests showed up.  I completed the 2 quests at level 40 but it won't let me turn in the quests or even abandon the quests.

**Comment by musictopia** [comment]
The problem even happened on my egyptians as well.  For that one, I previously did ready to build some farms so the problem only happened with up for a bit of fishing.

**Comment by Ryddag** [comment]
Still present?

**Comment by Zeentch** [comment]
I played egypt the other day, i was able to complete the quests without any issue, however i am not level 40 on them so don't know if it's linked to lvl 40 or not.
