### ISSUE TITLE
Trying to repack a 20 slot warehouse...

### ISSUE THREAD

**Issue by doddianca** [ProjectCeleste/Celeste_Server#219]
Trying to repack a 20 slot warehouse in my Persia civ to replace with a 24 slot, pop up window said I could not repack this building.  It is empty, I moved items from one to it, and repacked that one to replace it.  However, when I have moved everything back to new one, this one still empty will not let me repack it, and when I click on an empty space I get tossed from the game server.

**Comment by Jole1** [comment]
Make sure you have slot in your inventory

**Comment by doddianca** [comment]
I have a full 16 slot open, the one that you get when you start, trust me when I post something here it is an issue or problem.

**Comment by Ryddag** [comment]
Not an issue you can't repack default warehouse (1 normal civ, 2 pro civ)
