### ISSUE TITLE
Can't place workshops

### ISSUE THREAD

**Issue by panicx** [ProjectCeleste/Celeste_Server#221]
Hey, I play egypt

Before my disconnect today at 17:00 I was able to place all different workshops, after the disconnect my already placed rare workshops had disappeared. I tried placing them again, but the Gem Cutters Workshop, Toolmakers Workshop and Alchemists Workshop could not be placed again

**Comment by Ryddag** [comment]
8 workshop "basic" and 2 workshop "advanced" is the limit.
