### ISSUE TITLE
Missions aren't working at all sometimes

### ISSUE THREAD

**Issue by DaantjuhNL** [ProjectCeleste/Celeste_Server#222]
Look at the picture you do not see the mission objectives or the arrow to hide/show it. This means that a bug has occured and you do not progress towards any quest, sadly I noticed it at the 20 minute mark. ( I think this is coop exclusive)
![naamloos](https://user-images.githubusercontent.com/29275433/28748311-b9aea878-74b4-11e7-9a9f-edfed8e0a387.png)

**Comment by Ryddag** [comment]
This append only on Crete quest ? or you noticed this too somewhere else ?

**Comment by DaantjuhNL** [comment]
I did notice it 1 time before in a city defense/conquest game

**Comment by musictopia** [comment]
I noticed sometimes on even other missions once in a while.

**Comment by Ryddag** [comment]
Does those kind of issue still append? since it a one month issue maybe some other change we did fixed it.

**Comment by DaantjuhNL** [comment]
Never seen it again, so I'm fine with you removing it
