### ISSUE TITLE
Training time doesn't readjust when unit training is queued.

### ISSUE THREAD

**Issue by Goreshock** [ProjectCeleste/Celeste_Server#227]
I was playing Celts, and their upgrades to infantry training reduction time don't apply to units queued prior to upgrade completion. So here's the timeline to explain it better:

1. Queue 1 Long Swordman at Age 3 with no upgrade.
2. Queue upgrade.
3. Queue another Long Swordman.
4. Long Swordman finishes training in 10 seconds.
5. Upgrade finishes (Tooltip updates to say 8 seconds to train)
6. Long swordman still trains in 10 seconds.

Any other long swordmen you queue up AFTER the upgrade has finished train in 8 seconds.

**Comment by musictopia** [comment]
I think the original game was like this.  you had to wait for the upgrade to finish and once finished, new units train faster but not the ones in que.

**Comment by Ryddag** [comment]
yes it due to the game it self we can't fix this
