### ISSUE TITLE
Suggestion: Releasing some elite unit - advisors for babylonians and norse too

### ISSUE THREAD

**Issue by Teutonicus** [ProjectCeleste/Celeste_Server#228]
Hi, I want to make a suggestion.

What do you think about releasing some of the celtic, greek, egyptian and persian elite unit - advisors for norse and the babylonians?

Imagine how great it would be to lead war elephants as babylonians (also as persia would it be cool though) into the battlefield against your enemies.

I think there are many elite units, which fit well with other nations.  
Also barbaric units could function as mercenaries for more civilized nations. (and backwards)

It would bring up much more individuality and also wont harm the balance, so long your playing champion mode.

Please tell me what your thinking about it 🐘

**Comment by Ryddag** [comment]
Good idea, if you can post this here please : https://www.reddit.com/r/projectceleste/
