### ISSUE TITLE
Can't play coop while port 1000 - 1005 open

### ISSUE THREAD

**Issue by PsychoZzzorD** [ProjectCeleste/Celeste_Server#230]
Hi guys,

First of all thank you for bringing back this game, you're awesome.

We tried to play coop with two friend on windows 10 and it didn't work (I'm on windows 7 and can join other players without problem). 
We opened the port following the instructions of your website and it didn't worked.

We tried to shut off the antivirus, windows firewall, windows defender and it didn't work neither.

Do you guys have any suggestions what it could be ?

**Comment by Ryddag** [comment]
see this on discord help channel thx.
