### ISSUE TITLE
Legendary Beorix Returns not using the legendary loot tables

### ISSUE THREAD

**Issue by musictopia** [ProjectCeleste/Celeste_Server#233]
I discovered after playing the Legendary Beorix Returns that it was giving uncommon gear even though the loot tables show that legendary quests was not supposed to give uncommon gear for rewards.  This means the quest needed to use the legendary instead of general for the loot.

**Comment by jiffyette** [comment]
oh please, your so wrong bud, leg paphos / soloi / marion and crete still give uncommon gear , it comes down to pure luck with what u get

**Comment by KevinW1998** [comment]
Keep in mind that the chest from treasures still drop uncommon gear

**Comment by Ryddag** [comment]
Yes Legendary Beorix Returns use general loot table instead of general legendary loot table for quest reward its an error from original dev we while fix it later.

**Comment by musictopia** [comment]
Can I upload a fix for you on discord?  Because the fix is to change the reward in the quest file.  I have the quest file on project penelope.
