### ISSUE TITLE
Coin award bug when completing a quest.

### ISSUE THREAD

**Issue by M3SUT85** [ProjectCeleste/Celeste_Server#234]
Hi there,

There is a bug going around on some people that any quest with coin reward doesnt award you with coin although it makes the sound
my friend, myself and 3 other people on trade chat had the same issue
this didn't happen before the latest patch

Not sure if the developers are aware of it or not but I thought I should report it.

Thanks

**Comment by DaantjuhNL** [comment]
I can confirm that I did not get coin from persian coercion (2x) and legendary cataclysm since this patch

**Comment by fabsroman** [comment]
Any idea when this will deploy? Not worth questing until this is fixed.
