### ISSUE TITLE
Players not getting reward from skirmish or defense of crete

### ISSUE THREAD

**Issue by musictopia** [ProjectCeleste/Celeste_Server#237]
On coop, only the host appears to get any reward from skirmish or defense of crete.  Since I have not cooped any of them, I'm not sure but there are lots of comments about it on discord and in game.

**Comment by KhanAckhar** [comment]
Can confirm.

**Comment by Ryddag** [comment]
Does the today update fix this ?

**Comment by KhanAckhar** [comment]
According to other users, no, it did not fix the issue.

**Comment by KhanAckhar** [comment]
I have tested it myself now and i can confirm that the patch did not fix the issue.

**Comment by KhanAckhar** [comment]
Workaround: Every player has to host and finish skirmish game. After that, they will get rewards in co-op. 
Can't confirm for crete.
