### ISSUE TITLE
this is technically a issue / non issue = loot drops

### ISSUE THREAD

**Issue by jiffyette** [ProjectCeleste/Celeste_Server#238]
so the story - ive been playing celeste since it was announced. in this time there has been a lot of change to the loot table - the thing i want to draw attention to - that i believe should be changed for fairness to the community is the loot. in particular not the drop pr the frequency of the drop, but the level of each item.

6-8 weeks ago u could get lvl 40 blessed hammers., dionysus arm , etc etc , also line of sight existed on everything, fell handed gauntlet was -17.6 cost  not 7.9 (which it is now) . i think in fairness to the community it should revert back to the way it used to be, ( yes i have los) but i think everyone should  have los. 

thoughts ? i dont believe throwing the levels back  open and reintroducing los will break the game, in fact i think itll bring more people in.

**Comment by musictopia** [comment]
I agree with what he says.

**Comment by Wobling** [comment]
Agreed, there should not be a way to obtain loot that no one else can get, really throws balance out of the window.

This is why beta's generally reset after they're done.

**Comment by jiffyette** [comment]
while i personally dont want my gear to be lost, if it made the whole game fairer, and they reopened all the units , im up for a server wipe

**Comment by musictopia** [comment]
i would even agree to a server wipe as well so players have equal chances at how everything actually is in the game and players who played at the beginning would not have the unfair advantage.  One suggestion could even be a survey that players can respond as well like they have done with other decisions.

**Comment by jiffyette** [comment]
poll is a very good idea. lyris on pve captioned it perfectly = " im having more fun because my greeks are fully geared - lvl 37 vizier, lvl 40 bhoc etc " everyone should have this experience not just a select few. who were fortunate enough to be able to playh when the game tables were fully open

**Comment by Ryddag** [comment]
not the place for this
