### ISSUE TITLE
Elite Under The Wing Greek Capital

### ISSUE THREAD

**Issue by doddianca** [ProjectCeleste/Celeste_Server#239]
When doing this challenge, the rewards are supposed to be lvl 40 including a chance at a legendary item.  Did this run a few minutes ago and got lvl 37 chest rewards.

**Comment by jiffyette** [comment]
never ever had legs at that one man . usxes generql table

**Comment by doddianca** [comment]
That is why the color changes to 'orange' where it says level: any when you select elite.  It ups the chances to obtaining legendary items.  I have had a few legendary from it in the past 'original' game and this re-risen version.

**Comment by Ryddag** [comment]
does the reward in game has show at lvl 40 when set to elite for this quest ?

**Comment by doddianca** [comment]
When slection is made to elite the rewards chests jump from lvl 37 to lvl
40 I did the quest again last night but only was rewarded with two uncommon
and one common advisor.  I will test it out again later tonight, away for
the day today.

**Comment by Ryddag** [comment]
did you do it has coop ? if so host or not ?

**Comment by musictopia** [comment]
That quest is solo only.  There is no way for somebody to do it coop.

**Comment by doddianca** [comment]
I just got home will check it.
  But, I do not do coop or pvp.

**Comment by doddianca** [comment]
So I did the elite and shows rewards will be lvl 40, but to show you one of the three reward chests I got was a lvl 37 Diamond Staff of Hermes.  So something is not right there for sure.
![elite under wing lvl 40 reward chest](https://user-images.githubusercontent.com/29316464/29105061-59d2b20a-7c98-11e7-88fb-bc4dcad0a0a7.jpg)

**Comment by doddianca** [comment]
Verified Working Correctly now since update 8/13
