### ISSUE TITLE
Bug with Persian Quest Rewards (Under Pressure / Gate of All Nations, etc)

### ISSUE THREAD

**Issue by Zerrex** [ProjectCeleste/Celeste_Server#241]
I've noticed that the Persian capital city quests given by Darius, such as Under Pressure and Gate of All Nations (as well as the intro quest, the name escapes me) seem to have bugged rewards.

Normally, you can choose between half a dozen or so blue items and two white advisors, and you also receive a chest. I've noticed that when trying to select some of the equipment, it keeps giving me the advisors (and the guaranteed chest) as rewards, despite not selecting the former.

This bug has occurred for all quests that use this specific reward structure (both repeatables and the once off quests).

**Comment by Zerrex** [comment]
Update: Just completed it again. The rewards for these quests are, in order (Choose One):

Marathon Guard Spear, Long Spear of the Sun, Iron Wheel Spokes, Studded Ram Head, Comfy Sandals, Cast Nets, Curved Throwing Arm, Bronze-Sheathed Walls, Spiked Tower Shield, Infantry Sergeant Herakleides, Councilman Onesiphoros, Scaling Level Treasure Chest.

I just selected Spiked Tower Shield and was instead given Curved Throwing Arm. Trying to select the first two gave me the advisors instead.

It seems like the display order versus what you're actually given is shuffled or otherwise mismatched.

**Comment by KevinW1998** [comment]
Can confirm as this has happend to me too.
