### ISSUE TITLE
Bug with quest: War effort: xxx

### ISSUE THREAD

**Issue by durnich** [ProjectCeleste/Celeste_Server#245]
After completion of quest resources aren't substracted from inventory and therefore immediately repeatable.

**Comment by musictopia** [comment]
I don't see this as a bug.  If its true that it does not subtract from inventory, this is good so you can reuse the materials for something else.

**Comment by durnich** [comment]
In the way it works now I can get thousands of empire points for free by finishing the quest, getting it again immediately and finishing again. In a few minutes I can by what I want with empire points. This isn’t the intention. Empires points should be paid for with work, quests or time.

Regards,

Laurens van Beurden

Van: musictopia<mailto:notifications@github.com>
Verzonden: maandag 14 augustus 2017 16:16
Aan: ProjectCeleste/Celeste_Server<mailto:Celeste_Server@noreply.github.com>
CC: durnich<mailto:durnich@live.nl>; Author<mailto:author@noreply.github.com>
Onderwerp: Re: [ProjectCeleste/Celeste_Server] Bug with quest: War effort: xxx (#245)


I don't see this as a bug. If its true that it does not subtract from inventory, this is good so you can reuse the materials for something else.

**Comment by KevinW1998** [comment]
Can you tell me with which resource you have tried it? In which region did you try it?

**Comment by musictopia** [comment]
I can say for sure i tried it with the grains in delian and it did take away the resources.

**Comment by durnich** [comment]
It is in the region of Carthage and it are iron ignots. It still works for me.

Van: Kevin Waldock<mailto:notifications@github.com>
Verzonden: maandag 14 augustus 2017 19:30
Aan: ProjectCeleste/Celeste_Server<mailto:Celeste_Server@noreply.github.com>
CC: durnich<mailto:durnich@live.nl>; Author<mailto:author@noreply.github.com>
Onderwerp: Re: [ProjectCeleste/Celeste_Server] Bug with quest: War effort: xxx (#245)


Can you tell me with which resource you have tried it? In which region did you try it?

**Comment by durnich** [comment]
I will have another look, because I might be looking wrong.

I had so much iron that it might substract and I looked at the wrong pile.

Van: Kevin Waldock<mailto:notifications@github.com>
Verzonden: maandag 14 augustus 2017 19:30
Aan: ProjectCeleste/Celeste_Server<mailto:Celeste_Server@noreply.github.com>
CC: durnich<mailto:durnich@live.nl>; Author<mailto:author@noreply.github.com>
Onderwerp: Re: [ProjectCeleste/Celeste_Server] Bug with quest: War effort: xxx (#245)


Can you tell me with which resource you have tried it? In which region did you try it?

**Comment by durnich** [comment]
I was looking at the wrong pile stack, it works just like it should do

**Comment by durnich** [comment]
Excusae me for the inconvenience, it works like it should

Verzonden vanuit Mail<https://go.microsoft.com/fwlink/?LinkId=550986> voor Windows 10

Van: musictopia<mailto:notifications@github.com>
Verzonden: dinsdag 15 augustus 2017 01:14
Aan: ProjectCeleste/Celeste_Server<mailto:Celeste_Server@noreply.github.com>
CC: durnich<mailto:durnich@live.nl>; Author<mailto:author@noreply.github.com>
Onderwerp: Re: [ProjectCeleste/Celeste_Server] Bug with quest: War effort: xxx (#245)


I can say for sure i tried it with the grains in delian and it did take away the resources.
