### ISSUE TITLE
Bug with consumables

### ISSUE THREAD

**Issue by lennip** [ProjectCeleste/Celeste_Server#247]
Hi, 
I just used an Heroic Aid epic consumable ([this one](http://ageofempiresonline.wikia.com/wiki/Heroic_Aid)) in a quest.

However, a problem occurred: before starting that quest I had a stack of 4x Heroic Aid, but after using it once I was left with only 1 (when there should be 3 left). 
So basically, clicking one time on a stacked consumable to activate it made me lose 3 units of it at once, instead of just one.

I think the problem comes from the latest patch, since I used the very same consumable previously in another quest and it worked fine. 

Can anyone confirm this? Thanks!

**Comment by Ryddag** [comment]
#182
