### ISSUE TITLE
storage repack

### ISSUE THREAD

**Issue by CptDashRendar** [ProjectCeleste/Celeste_Server#248]
persian 20 slots storage cannot be reppacked in order to add empire storage

**Comment by Ryddag** [comment]
Original warehouse can't be repack, so pro civ have 2 like this

**Comment by CptDashRendar** [comment]
![2017 08 19-22 17](https://user-images.githubusercontent.com/29496215/29492075-5031c1f8-852d-11e7-8383-c44ba48b3275.png)
![2017 08 19-22 19](https://user-images.githubusercontent.com/29496215/29492076-5035cc12-852d-11e7-95e3-1d24300b7830.png)
OK thank can we have then the 16 slots on at the top, as it is on the norse, I haven't tried babys because I do not have the stashur. Thank you so much for your great work.
