### ISSUE TITLE
Babylonian Siege Towers accepting Cavalry.

### ISSUE THREAD

**Issue by Ca-Putt** [ProjectCeleste/Celeste_Server#253]
The Siege tower currently seems to be able to transport not only Infantry but also Cavalry. This is not limited to mounted units that are tagged as Ranged but also just regular melee Cavalry. (it also accepts Priests and Vills btw but those are ok)

- (full)Siege towers only count as 1 towards the Transport limit of Transport ships.
- This Problem may extend to Oxcarts(but I have not unlocked that tech yet).

**Comment by musictopia** [comment]
I can say for sure in the original game, the babylonian siege towers also accepted cavalry.

**Comment by Ryddag** [comment]
Not an issue, its like the game is made, it work like an boat and can transport any unit.
