### ISSUE TITLE
Champion mode for Skirmish

### ISSUE THREAD

**Issue by KhanAckhar** [ProjectCeleste/Celeste_Server#258]
I think that most people would prefer if Skirmish would use Champion mode.

-It would be more balanced since gear doesn't count, meaning low levels and high levels have the same chance of beating AI
-You could use Skirmish hall to train for PvP since the PvP tech tree would be used
-It would give players an old classic Age of Empires feeling because they are able to play like they used to.

I think, since PVP matches are quest files and skirmish matches are quest files, that it's somehow possible to accomplish that. 

It would be great if you could consider making this change, perhaps create a poll and ask people if they would prefer a champion mode for skirmish or the old gear based mode.

**Comment by musictopia** [comment]
There is already a special mode for skirmish where the enemy uses the same gear the human has.  That is actually close to champion mode because if the human has no gear then the enemy will have no gear.

**Comment by KhanAckhar** [comment]
That might be true, but that's not what me and a lot of other people are asking for. The customizable skirmish hall has to use champion mode to be fun and interesting for most aoe players. Especially those coming from aoe2

**Comment by cad39again** [comment]
1. I no see "a lot of other people are asking for".
2. Isn´t pvp, is skirmish

**Comment by KhanAckhar** [comment]
Skirmish has always been an "offline" or "bot" mode of PvP in literally every other RTS game. It was a bad choice for Microsoft to change that concept here.

**Comment by Zeentch** [comment]
I wouldn't mind it having a champion mode that you could select but not make it so you can't chose, i know a lot of people are using the skirmish hall for farming specific level chests and taking that away would reduce the amount of items being sold, and it'd be virtually impossible to improve upon gear that has a lower lvl once you hit 40 if this change were to happen.

**Comment by KhanAckhar** [comment]
I talked about this with Kevsoft and he said that creating UI elements (for example a button to choose between champion and standard mode) would be harder to do than enabling champion mode.

I would also prefer to have a choice but i guess that will never happen.

About that farming thing: I never asked to remove the rewards. People will still be able to get rewards by completing skirmish games. I just think that making the gameplay PvP like will improve the overall user experience.

**Comment by M3SUT85** [comment]
Don't touch any existing things on PVE please. If you want to play "champion mode" there is that option in pvp.. if you want to play versus AI in champion mode I suggest a few new quests.. but don't change the way the existing quests are.
