### ISSUE TITLE
Advisors disappearing

### ISSUE THREAD

**Issue by musictopia** [ProjectCeleste/Celeste_Server#26]
I've had cases for ages 3 and 4 advisors where I would choose an advisor and somehow it would show the advisor was not selected after all.  I can still choose advisor again.   However, its annoying to get to a quest and find out nothing was selected for an age even though I did select one.  Not sure if it happens after logging off or not.

**Comment by musictopia** [comment]
One user thinks the issue could be related to when purchasing an advisor from a shop.  I think that is one possible pattern.

**Comment by onlinemindgem** [comment]
Can confirm this one. Bought counsilman, selected it, played a few quests with it, and suddenly it was deselected and not avaliable in a quest

**Comment by onlinemindgem** [comment]
I believe this happens (sometimes / with specific advisors) at new logon

**Comment by WiriWout** [comment]
Happened to me also from 2 advisors bought from the argos shop.
