### ISSUE TITLE
Crafted items always have standard stats

### ISSUE THREAD

**Issue by lukipr0** [ProjectCeleste/Celeste_Server#262]
I see I didn't provide enough Information earlier. So here it goes:

Crafted items DID in fact have variable stats just like dropped items. Standard +/- 4.5%.
Example: In the original game I had the epic item recipe for Epona's Boar-Hide Boots Lvl 28 [http://aoedb.net/items/1591/28](http://aoedb.net/items/1591/28). Standard stat is +6.8% movement speed. I crafted them by the hundreds and only sold 7.1 MAX ones, the rest went straight to the vendor.

Everyone who crafted items on a regular basis will confirm this.

**Comment by Ryddag** [comment]
The blueprint contain fixed stat value, and it was same in original game if i remember well only reward from chest have rnd stat.

**Comment by KevinW1998** [comment]
I am honest.... I am not sure... because I have the feeling it did have randomized values... I've tried to find evidence on YouTube but no luck do far

**Comment by Ryddag** [comment]
Did you find any info on this ? for me its fixed value because stat are showed before creation. After we can easilly add rnd stat for them too
