### ISSUE TITLE
Port Issue

### ISSUE THREAD

**Issue by cl0udedth0ught** [ProjectCeleste/Celeste_Server#263]
I am trying to set up port forwarding on my wife's computer so we can both play with others online. It wouldn't seem to work without it. My other friend and I were able to connect and play online once we did the port forwarding. 

Is there a way to change the Private/Public Port from 1000 for her computer? It is grayed out when you go to the MP settings.

**Comment by Ryddag** [comment]
No port 1000 is fixed, only way to coop online with two user on same network is to use hamachi
