### ISSUE TITLE
AOEO Servers is not avaible this time

### ISSUE THREAD

**Issue by Hidannie** [ProjectCeleste/Celeste_Server#264]
This is annoying... When im in a quest, or in capital, game shut down and says, "Age of empires online servers is not avaible this time". And after that, i can join server again. And i checking my internet connection, my internet doesnt gone or smthing. I get this issue so very much. Especially in quests. And sometimes it appears in 20 or 30rd Minutes of game...

**Comment by NCSGeek** [comment]
This isnt an issue on their end, this belongs in the help channel on the discord.

Contact #help here: [https://discord.gg/sE9dCaW](Discord)
