### ISSUE TITLE
OUT OF SYNC

### ISSUE THREAD

**Issue by Lyris2000** [ProjectCeleste/Celeste_Server#265]
Im getting a lot of out of sync l;ately ,when we replaced the spartan file it was fixed no problem ,last week im getting always out of sync when i play marion legendary and today got twice in new leg quest the end of traitors

**Comment by Ryddag** [comment]
when did you get thoose error after some times ? or only at game start ?

**Comment by Lyris2000** [comment]
sometimes it happens early on a quest sometime after  ,but its been a lot better from the day i reported it

**Comment by Lyris2000** [comment]
after the latest patch im getting out of sync eveytime i play mileto legendary and sardes

**Comment by Lyris2000** [comment]
it might be my connection i dont know but it happens to me alot

**Comment by luciano7** [comment]
this is happening on co-op games I'm assuming? @Lyris2000

**Comment by Lyris2000** [comment]
yes only on coop
