### ISSUE TITLE
CREATE or SELECT the capital city map

### ISSUE THREAD

**Issue by BigMinnie** [ProjectCeleste/Celeste_Server#269]
[Reddit post](https://www.reddit.com/r/projectceleste/comments/71zgjw/capital_city_map/)

So I really love to create and play with the style of the capital city, but there are on few nice maps and even harder is to get them. So I was thinking, that it could be nice, to have a map selector for our capital city. So how it would work? There could be a simple UI with list of the maps (BONUS: maybe a image next to them). When you select the map you could preview them if you like it, you select it and play with it. After the time you could also add your own maps to the list. 

BONUS: You could transfer your capital city over to the new map in game. It would cost EP or a lot of gold and it could be a nice reward for us that are enjoying with styling our capital city.

OR just make that we could create our own map with the map editor but the problem is, that the map need x % of water (for dock) and x % of land for all the buildings you need to play.

**Comment by BigMinnie** [comment]
bum, stil no info from devs 😞

**Comment by Ryddag** [comment]
https://forums.projectceleste.com/posts/117/
