### ISSUE TITLE
chat some times working some times not

### ISSUE THREAD

**Issue by hammodeh88** [ProjectCeleste/Celeste_Server#270]
most times the chat not working for me . I choose trade or general and no thing is appearing in the chat box . I tried to go to channel optins and make the channel to trade channel and nothing happened . fue times the trade channel and the general channel working auto and the things works normally (but this is feu times). I need your help to solve my chat problem . please help me .

**Comment by Hidannie** [comment]
I know that. You write something, you can not see what u write but they can see. its annoying.

**Comment by maodia** [comment]
that happens sometimes.if you have two computer and login the game with two id seperately,you can see that not all the message displayed on the two computer,some displayed only on computer a ,and not displayed on computer b.

**Comment by Ryddag** [comment]
Its due to udp package who are tracked and so can't sometime be lost. Its more an client side issue about connection, not server that why other user can see the message and not you.
