### ISSUE TITLE
divine hammer of construction bug

### ISSUE THREAD

**Issue by jiffyette** [ProjectCeleste/Celeste_Server#271]
theres a big in divine hammer, when equioped u get the construction bonus but not the gather bonus.

all my villies still do 10 with it equipped. . please fix

**Comment by MrMuggs** [comment]
I tested this just now, devine hammer is showing dropoff of +10 at storehouse but is actually adding 11, with first TC upgrade is 13 and 2nd is 16, same as blessed hammer level 40, so it does have the small carry bonus.
