### ISSUE TITLE
Empire consumables not usable at age 1 (non sense as it supposed to help low lvl or low equiped)

### ISSUE THREAD

**Issue by depotnet** [ProjectCeleste/Celeste_Server#283]
OK, I read it's part of the patch note (Changelog of June the 22th)

But those can be "banned" from skirmish to prevent rush and easy win.

**Comment by Ryddag** [comment]
"non sense as it supposed to help low lvl or low equiped)" is was supposed to be paid cheat to allow money income in game ...
