### ISSUE TITLE
New issue- Game initialization failed 

### ISSUE THREAD

**Issue by Tomislav31** [ProjectCeleste/Celeste_Server#284]
First time trying to launch the game 
I Press the play button and this comes up Game intialization failed please do a full scan in the launcher and try again (CORE). 
I don't know how to fix
Could anyone help

**Comment by Ryddag** [comment]
you need to enable direct play.

https://www.reddit.com/r/projectceleste/wiki/how-to-install-and-play-aoeo-celeste-fan-project#wiki_4.3A_troubleshooting

**Comment by Tomislav31** [comment]
Thanks for the initial helpBut i am confused on what link to download Is there a specific one i need to download or is there a actual direct play link 

    On Thursday, 19 October 2017, 7:29, Ryddag <notifications@github.com> wrote:
 

 you need to enable direct play.https://www.reddit.com/r/projectceleste/wiki/how-to-install-and-play-aoeo-celeste-fan-project#wiki_4.3A_troubleshooting—
