### ISSUE TITLE
COUNTDOWN FOR THE RELEASE OF THE REPEATABLE QUESTS

### ISSUE THREAD

**Issue by legendhero** [ProjectCeleste/Celeste_Server#286]
Hi there, Developers! First of all, congrats for the good work and finally the loot is a lot better! I have an important  suggestion that maybe your team could implement in the next patch very easily (i suppose) and that many players are talking about: everyone would love to have a countdown for the release of the next quest (for the repeatable ones). Its very confusing for the players as it is now because we have a lot of civs and with a lot of similar quests, and we have to always be checking if we already can repeat some of them, many times without having any idea how long we will still have to wait for it. Even in the old times of this game, players were already asking for that countdown, but microsoft never listened to us. Would it be possible to do, at least in the legendary quests? Would be very very nice if we could see an entire list with all the legendary quest countdowns when we were in our capital city. That way, we didnt had to go from city to city and from quest to quest to check if we already have it to play again. What do you think of this idea?****

**Comment by Ryddag** [comment]
can't be add to game since it require to be able to "edit" the game code it self (spartan.exe)
