### ISSUE TITLE
Bugs when reaching age 40

### ISSUE THREAD

**Issue by musictopia** [ProjectCeleste/Celeste_Server#29]
The last quest I did that got me to level 40, when I marked as complete, nothing would happen.
Then I logged off and logged back on.  It did show the next quest and me at level 40.  The bad news is I was unable to use the last tech point I was supposed to receive from reaching level 40.  Also, the experience bar was not all the way to the right either.

**Comment by Ryddag** [comment]
You miss one tech point only or more ?

**Comment by musictopia** [comment]
I am only missing that one point.  Even at level 39, it shows one tech left to get.  This means that at level 40, does not unlock the final point.  Another issue is the 10 empire points for reaching level 40 does not happen either.

**Comment by onlinemindgem** [comment]
I'm 40 and have full tech. Still need to fill up the xp bar of the level.

When moving to 40 got 1 point, Alliance war notice and the new quest legendary catalism.

**Comment by musictopia** [comment]
For me what happened was it would not allow me to turn in a quest.  Then when I logged out and logged back in, then it showed me at level 40 but never received my last tech point, or the 10 empire points for reaching the last level.  Showed the next quest in the quest line but never got rewards from the completed quest.
