### ISSUE TITLE
Coop - Partner not exist or not connected

### ISSUE THREAD

**Issue by Zarlokh** [ProjectCeleste/Celeste_Server#291]
Hi, sorry for my bad english i'm a poor french :'(

With my friend, we use hamachi (configure in MP Settings) to play together. But randomly when we launch a quest we have the error message 'The Player <friendname> does not exist or not  connected' even he is connected and in my group.
The error occurs very often :'(
It is therefore hard to play together :(

**Comment by Ryddag** [comment]
Alors quand la quêtes démarre une connexion client a client (p2p) est initier entre vous.
Apparemment cette connexion échoue quelque fois c'est pour cela que tu reçois ce message car tu n'arrive pas a joindre ton coop en connexion direct (p2p).
