### ISSUE TITLE
Production of material stops and doesn't restart IF reach its max stack

### ISSUE THREAD

**Issue by depotnet** [ProjectCeleste/Celeste_Server#292]
This morning, I logged into my account and switch on my CIV to get the material production

All common material productions were stopped.

I contacted one of my friend who is also playing AOEO, same issue

**Comment by depotnet** [comment]
I think I found the reason : if production reach its max stack (ie 100/100 for common material) production stops and doesn't restart automatically if you empty it

**Comment by Ryddag** [comment]
its how it work when the stock is full it stop all production, that why their is an max.

**Comment by depotnet** [comment]
Normally when you take the full stack from the workshop, the production starts over automatically
