### ISSUE TITLE
Peepaw quest loot won't loot

### ISSUE THREAD

**Issue by TheRealAJL** [ProjectCeleste/Celeste_Server#303]
Some help with an incidental bug please:
Several times played Peepaw now, but today de maple saps didn't disappear when the quest was completed, so I destroyed them in order tot make room in my inventory. The only thing is that choosing complete quest doesn't complete the quest and doesn't give the loot-chest. It does nothing.
thnx for the help,

**Comment by KevinW1998** [comment]
Tried not reproduce but for me the quest worked. Could you maybe record a video when you try it again?

**Comment by TheRealAJL** [comment]
I understand. I suspected something like that (an incidental bug)
Situation on my account still exists though. Can you solve that, buy resetting it?

**Comment by TheRealAJL** [comment]
I solved it. I abanded the quest, so it restarted and give me the opportunity to play it again. Now I could complete the quest as I always do. 

I also think there's a way to reproduce the error. Your storage must be full except for de 5 maplesap-chests to fill up during the quest. Then when you reached all the goals of the quest exit it as you would normally do. Your storage is now complete full when pressing "complete" to collect the questloot there will be prompted something like: there's no storage available. Then you destroy all the maple sap items (5x) and although you have storage space again, you can't collect the questloot by pressing "complete". .....So you have to abandon the quest and start over with 6 empty storage slots.
