### ISSUE TITLE
No vender price for new mats

### ISSUE THREAD

**Issue by Cubicals** [ProjectCeleste/Celeste_Server#308]
I cleaned out my workshops and the mats sold for nothing to the vendor wile the ones i had before had a vendor price. by combining a priced mat over onto an unpriced mat stack you can make it sellable. 
![age of empires online screenshot 2017 12 31 - 10 19 21 28](https://user-images.githubusercontent.com/34985268/34467860-82493eb2-eeca-11e7-9931-a02f0dc143d7.png)
![age of empires online screenshot 2017 12 31 - 10 19 33 32](https://user-images.githubusercontent.com/34985268/34467862-8778c6d2-eeca-11e7-992c-a8abbccb22c0.png)
![age of empires online screenshot 2017 12 31 - 10 19 46 89](https://user-images.githubusercontent.com/34985268/34467864-88cef948-eeca-11e7-96ca-7127ba7ae7e3.png)
![age of empires online screenshot 2017 12 31 - 10 19 50 91](https://user-images.githubusercontent.com/34985268/34467866-8a12c8f2-eeca-11e7-96d0-3e0d64acd86b.png)
![age of empires online screenshot 2017 12 31 - 10 20 18 28](https://user-images.githubusercontent.com/34985268/34467868-8b51de74-eeca-11e7-9710-990bbb0ff8cc.png)
![age of empires online screenshot 2017 12 31 - 10 20 21 90](https://user-images.githubusercontent.com/34985268/34467869-8c8d26fe-eeca-11e7-9e51-31939ce90440.png)

**Comment by Ryddag** [comment]
https://forums.projectceleste.com/threads/material-stacks-do-not-give-gold-if-vendored.104/
