### ISSUE TITLE
Material Workshops not placeable in capital city

### ISSUE THREAD

**Issue by Taisamba** [ProjectCeleste/Celeste_Server#31]
Once bought, I cannot place any of the material workshops in the capital city. The building preview shows up, but it just doesn't place it down to begin the building.

**Comment by musictopia** [comment]
I thought that crafting was not working.  I found the same thing where it just won't let the player place the crafting building.

**Comment by Taisamba** [comment]
I have a feel that it is something related to the server, since you have it to put in your capital city and produces mats at a time rate, I think server time or something?

**Comment by deefbert** [comment]
Can confirm; at least the logger's workshop is not placable for me. That said, they don't work yet anyway.

**Comment by Ryddag** [comment]
#4
