### ISSUE TITLE
Initialization Failed

### ISSUE THREAD

**Issue by starikcetin** [ProjectCeleste/Celeste_Server#314]
https://forums.projectceleste.com/threads/game-wont-launch.181/

I could launch and play the game in multiplayer with the previous launcher, since the new launcher replaced the old one I get this error after the game file check when I press Play:

![capture](https://user-images.githubusercontent.com/21353964/35482626-0777eb4a-0449-11e8-9cbf-fb0fa55ba8ce.PNG)

Already tried:
- Everything on Reddit article troubleshoot section. (I uninstalled every one of them and reinstalled them)
- Disable/re-enable DirectPlay.
- Full reinstall of the game.
- Disabling my antivirus.
- Compatibility mode.
- Launch as admin.
- Game scan.

I'm on a Windows 10.

**Comment by Wartai** [comment]
Usually caused by a bug when you enable Beta in launcher, disable Beta, Game Scan and try joining, if successful, then try enable Beta, then game scan if you want to play Sparta PVP

**Comment by Ryddag** [comment]
we will continue to handle this issue on the forum
