### ISSUE TITLE
Materials are not consumed when building

### ISSUE THREAD

**Issue by Taisamba** [ProjectCeleste/Celeste_Server#32]
Materials are not consumed when used for blueprints in the Capital city.

**Comment by musictopia** [comment]
Actually, this is not an issue and is actually a good thing because this means that if you have the materials, you can reuse those materials.

**Comment by Taisamba** [comment]
Yeah it is good for testing if the buildings work correctly

**Comment by Nade1911** [comment]
This is acually important materials should be consumed when u build lul
