### ISSUE TITLE
Legacy xlive and friend list

### ISSUE THREAD

**Issue by Finishedblock21** [ProjectCeleste/Celeste_Server#325]
When I switched to legacy xlive my friend list got wiped and I'm not getting any friend notifications. I can still see friends in the game launcher. Re-adding them doesn't help either. (I switched xlive as the Sparta one would cause my game to crash when turning in quests sometimes, no crashes with Legacy)

**Comment by KevinW1998** [comment]
Legacy xlive is very restricted and limited only to necessary features. If you experience crashes then please enable "Diagnostic Mode" in the launcher and run the game with sparta xlive. When you encounter a crash again then send me the crashdumps located in `My Documents/Spartan/MiniDumps`

**Comment by Finishedblock21** [comment]
Thanks for the fast response! Will the crashdumps get created automatically if my game freezes and how do I send it to you?

**Comment by KevinW1998** [comment]
Contact me on discord

Am 07.04.2018 17:43 schrieb "Finishedblock21" <notifications@github.com>:
