### ISSUE TITLE
Quest A Few Good Men not handing in

### ISSUE THREAD

**Issue by Smedslund** [ProjectCeleste/Celeste_Server#35]
Watch:

https://www.youtube.com/watch?v=UCrM8HBfH4E

**Comment by Ryddag** [comment]
Do you have free slot in your inventory ?

**Comment by Taisamba** [comment]
I had the same problem, I got everything except the advisor. I relogged and the quest disappeared.
Still no advisor.

**Comment by Daddysds1** [comment]
You can turn the quest in but it stays there until you relog and then it acts as if it was turned in. But you don't get the advisor. Not to concerned about the advisor. But it does indeed have a few issues.

**Comment by Thin029** [comment]
#40 It's just like this, sorry.
