### ISSUE TITLE
Alpine Escort not completeable

### ISSUE THREAD

**Issue by IamMidas** [ProjectCeleste/Celeste_Server#36]
In the mission should be a trade building : https://www.youtube.com/watch?v=lm-TJSbOxUs#t=8m06s like here. There is no building like that in celeste.

**Comment by IamMidas** [comment]
oh i justed tested every quest of engineer farzana, which include objectives "collect x" . None of these work.
"The Last Cascade"
"Don't cry for me Farzana"
"Den of Thieves"
"Lost Island of King Tusk"

**Comment by Ryddag** [comment]
Thoose quest has special loot table, i need to create them.
