### ISSUE TITLE
Selection does not register 

### ISSUE THREAD

**Issue by WiriWout** [ProjectCeleste/Celeste_Server#37]
In some occassions, dragging a box around units does not result in selecting them. Here's a link of a clip where it happens when trying to dragbox 4 priests:

https://clips.twitch.tv/RefinedCrowdedChickenDancingBaby

However, I've also had it happen in a different quest, when I was trying to drag a box around my army (not containing any priests).

**Comment by Ryddag** [comment]
Game issue not server

**Comment by luciano7** [comment]
Closing issue since we can't fix issues on the .exe.
