### ISSUE TITLE
Bronze Age Technology quest

### ISSUE THREAD

**Issue by Wobling** [ProjectCeleste/Celeste_Server#39]
Completed and turned in but doesn't actually complete stays able to hand in with no rewards given.

**Comment by Semperfi0817** [comment]
I too had this bug. Not sure if this is helpful but the quest is to upgrade any technology in the bronze age. However, I had already used all my points before accepting this quest so when I first clicked on the advisor to learn about the quest it already showed as completed. I tried resetting the points but still clicking on the complete the quest button did nothing. I closed out and relaunched the game and that quest was gone however, I received none of the rewards. Not too big of a deal and at least a new quest is now available.
