### ISSUE TITLE
Quest - GET THE GOODS - Cannot be Completed

### ISSUE THREAD

**Issue by BOSAIF86** [ProjectCeleste/Celeste_Server#41]
I tried to submit the quest GET THE GOODS but it doesn't work!

EDIT: For some Odd reasons Re-logging solved the issue; however, I don't think I received the rewards ..

**Comment by BOSAIF86** [comment]
For some Odd reasons Re-logging solved the issue; however, I don't think I received the rewards ..

**Comment by deefbert** [comment]
Confirmed, happened to me with the same quest.

**Comment by Semperfi0817** [comment]
I could get in and play for about 30 to 40 minutes but kept getting server error. Not sure if this is a bug for this quest or if there were really server issues.
