### ISSUE TITLE
Quest - FISHING OUR WATERS - Cannot Be Completed

### ISSUE THREAD

**Issue by BOSAIF86** [ProjectCeleste/Celeste_Server#43]
The quest "fishing our waters" can't be passed.

EDIT: Upon re-logging, the quest was passed without getting any rewards, no items nor EXP gained!

**Comment by deefbert** [comment]
Confirmed. Got the quest XP upon the first time clicking "accept" though (possibly the gold, I'm not sure). Didn't get the equipment, and the quest giver is still showing a ?.
