### ISSUE TITLE
No starting EP

### ISSUE THREAD

**Issue by deefbert** [ProjectCeleste/Celeste_Server#44]
The game used to reward Empire Points upon levelling up (the table's on http://ageofempiresonline.wikia.com/wiki/Empire_Points) and to let people start with 100 EP (500 for old accounts). Neither is implemented yet.

**Comment by musictopia** [comment]
The game goes award empire points for leveling up.  The only part that does not work is the part for getting from 39 to 40 which is probably related to a bug I reported earlier.

**Comment by deefbert** [comment]
Well, either that isn't working or quest reward EP isn't working. I'm at level 6 with 5 EP, and I got a few EP from quest rewards. I'll keep an eye out on my next level-up.

**Comment by deefbert** [comment]
Checked again, levelling up from 6 to 7 gave 2 EP, working as intended, finishing a quest for 2 EP worked too. Don't know where I lost EP earlier.

I suppose the 100 starting EP still aren't there.
