### ISSUE TITLE
Quest can't be turned in

### ISSUE THREAD

**Issue by deefbert** [ProjectCeleste/Celeste_Server#45]
This has happened twice so far, now with "Get the Goods". Upon finishing the quest and selecting a reward, nothing happens when I click "accept".

Upon re-logging, it had made the next quest in the line available (this didn't happen a week back, when it left me stuck and I had to make a new city to progress), but I still didn't get any of the quest rewards.

**Comment by luciano7** [comment]
closing duplicate
