### ISSUE TITLE
chests not being given properly in quest for elite / legend

### ISSUE THREAD

**Issue by jiffyette** [ProjectCeleste/Celeste_Server#51]
ive noticed while do a lot of elite quests , chests arent being given properly. 

i just did elite end of the line - its 5 chests given if stay in age 2, plus 4 treasure chests. when i turned in the completed quest, i only had 5 chests to open. missing 4. ive noticved this happening on rogues, what a ego maniac, and others.

**Comment by Ryddag** [comment]
#2
