### ISSUE TITLE
ambrosia project / den of thieves.

### ISSUE THREAD

**Issue by jiffyette** [ProjectCeleste/Celeste_Server#52]
on the quest - den of thieves, this opens upo when u start the ambrosia project. 

on den , once u mine out all the stone, theres a chest at the end ( after killing the guardians), the chest when opened is meant to give u a sesame seed. well upon completion i didnt get a seed i got a net for fishing .

i remember this being a issue in the online game, until they patched it with the summer patch. 

so i assume it will need patching, ambrosia isnt able to be completed

**Comment by Ryddag** [comment]
#36
