### ISSUE TITLE
Xlive replacement: Invalid credential makes game crash

### ISSUE THREAD

**Issue by onlinemindgem** [ProjectCeleste/Celeste_Server#54]
Xlive replacement: Invalid credential makes game crash

**Comment by deefbert** [comment]
Confirmed. Doesn't make the celeste gui crash though. If this crash happens, that needs to be killed too before retrying a login.

**Comment by deefbert** [comment]
Update: This crash happens when you alt-tab out while the Celeste login pop-up is up. Anything that causes Celeste to lose focus (or Aoeo to gain it) causes this crash.

**Comment by Enveee** [comment]
Ok its just an error on you're **Password** or you're **Mail** don't forget to respect caps !
I got this error cause i forget a cap in my mail

**Comment by MrPSIHO13** [comment]
runtime error,replace file call
