### ISSUE TITLE
Utility tab of tech tree missing background texture

### ISSUE THREAD

**Issue by Daeveren** [ProjectCeleste/Celeste_Server#56]
Utility tab of tech tree missing background texture - shows all white, but only the 3rd (Utility) tab. The other tabs have the proper background. On Egyptians civ.

![image](http://i.imgur.com/8Xm2Isb.png)

**Comment by Taisamba** [comment]
I have the same issue, but all except milestone background are missing and showing white as the screenshot above.

**Comment by Daeveren** [comment]
Restarting game fixed the issue. You guys choose if to mark it as low importance or just close the issue.

**Comment by Daeveren** [comment]
Update: another game restart, the same issue from screenshot happens again (only for Utility tab).

**Comment by Daeveren** [comment]
Definatelly something happening. I'm running the game with the same settings as before the update with new auth system (windowed borderless).

![1](http://i.imgur.com/F76Wzns.png)

**Comment by musictopia** [comment]
i had cases where everything showed white until i would completely restart the game.  however, eventually the same problem happens again.

**Comment by musictopia** [comment]
today, i did not have the problem after using the new xlive.dll which was published later yesterday.

**Comment by olibeu** [comment]
Hello, had the same issue with the missing bckground and switched between windowed mode and full screen (Alt + Enter) and it seemed to fix it for me.

**Comment by Daeveren** [comment]
I think this should be fixed now with the Celeste B102 zip

**Comment by Ryddag** [comment]
B102 seem to fix it.
