### ISSUE TITLE
Wrong icon displayed on the items in inventory

### ISSUE THREAD

**Issue by Daeveren** [ProjectCeleste/Celeste_Server#59]
The icon from another item is displayed over my item in bags. See the 2 screenshots below (mouse cursor also shown).
Only saw it for the first 3 items on the 1st line of inventory (4th item shows ok).
Restart did not fixed the issue.

![1](http://i.imgur.com/4Ew0Ulu.png)

![2](http://i.imgur.com/Ed2jhb8.png)

**Comment by musictopia** [comment]
I had the same issue with other things.  This happened on my egyptians ones.

**Comment by Ryddag** [comment]
Will be fixed in today update

**Comment by Neonerd1** [comment]
I have the same issue with the item called Pirate Fire Ships. It shows a breastplate icon and I can't sell, or move or destroy the item.
Also with the Item called Bandit Archers It shows an equipment but can't be sold or destroyed.
