### ISSUE TITLE
sandstorm egyptian, error

### ISSUE THREAD

**Issue by jiffyette** [ProjectCeleste/Celeste_Server#61]
sandstorm on eggy civ has a error, load it up , it says map wont load . :(

**Comment by musictopia** [comment]
it loaded up on my with no problem.   may be a problem that only affects some.  try to log out and log back in to see if it works.

**Comment by WiriWout** [comment]
Worked for me

**Comment by jiffyette** [comment]
it worked after i deleted steam api (again) :(
