### ISSUE TITLE
Getting materials from quests

### ISSUE THREAD

**Issue by musictopia** [ProjectCeleste/Celeste_Server#63]
In the original game, a player would never get materials for completing quests.  I think the loot table when somebody completes the quests should be anything except for materials, or broken items.

**Comment by onlinemindgem** [comment]
Not completely sure, I do believe one could get basic mats, but I got Delphi Limestone from quest. That doesn't seem right.

**Comment by MrPSIHO13** [comment]
its good hehe,no need for questing :)

**Comment by musictopia** [comment]
The only case where a person gets materials from quests is the trade quests since they know ahead of time they are getting the special materials.

**Comment by Ryddag** [comment]
I will call this bad luck, materials has the lower rate chance ^^

**Comment by musictopia** [comment]
I have found a player seem to have a much better chance of getting materials than even advisors.  Maybe advisors should be a little more common.  I've only twice gotten any advisors.

**Comment by MrPSIHO13** [comment]
i didnt get any

**Comment by Ryddag** [comment]
Actual loot chance: 10% Adv 10% Mat 10% Consumable 10% Design 10% BP 10% Vanity 10% Gear 40%
And of course also some sub-table for quality

**Comment by MrPSIHO13** [comment]
as far as i know that is all in charactermodifiers.xml yes (drop chance)
