### ISSUE TITLE
consumables dont work / heroic aid / inventory

### ISSUE THREAD

**Issue by jiffyette** [ProjectCeleste/Celeste_Server#64]
so i started egg. got to lvl 4, did a quest, got a los arduinnas bow, its in my inventory, but when i try and move said bow, it comes up as heroic aid. if i try and move heroic aids out of my inventory ( to delete them) they wont delete.

secondly my consumbles (including heroic aid, and others, ) dont work, in either civ, greek or egg. 

major problem !!! :)

**Comment by musictopia** [comment]
my consumables worked with no problems.  i did have sometimes where the item in the inventory is different from the picture.

**Comment by jiffyette** [comment]
yes but that doesnt help me mateits server side, i cant do anything to change it

**Comment by MrPSIHO13** [comment]
for me no consumable works
but it did before i log out and log in back

**Comment by jiffyette** [comment]
yes same no consumable work on egg

**Comment by Ryddag** [comment]
issue till present with today update ?

**Comment by francot514** [comment]
I can confirm some advisors and consumables does have problems with moving on inventory.

**Comment by Daddysds1** [comment]
libo - Today at 11:06 PM
chests go to the same slots with hippikon and heroic aid and i cant open them

Libo can confirm  this is also an issue
