### ISSUE TITLE
Item stuck in warehouse slot

### ISSUE THREAD

**Issue by MrPSIHO13** [ProjectCeleste/Celeste_Server#66]
i have one consumable stuck in inventory and i cant delete,use,sell or move it
but i can place him in consumable 4 slot bar

**Comment by jiffyette** [comment]
i have the exact same issue, however mine also stops me from using the consumable across that civ, if i log out, and log in dif civ, cant use consumable. so happy someone else has the issue !

**Comment by musictopia** [comment]
I have the same issue.  I think its the same issue where you mouse over an item and it shows a completely different item than what the image shows.  There was a gear that is stuck and when I mouse over, it says its consumables.  I originally had the consumables but somehow the inventory got messed up for me and logging off and back on does not fix the problem.

**Comment by Ryddag** [comment]
If someone still has this issue PM me on discord
