### ISSUE TITLE
Egyptian warehouse not building and eating away materials

### ISSUE THREAD

**Issue by Taisamba** [ProjectCeleste/Celeste_Server#68]
Trying to build 12-slot warehouse as well as 16 slot, the 16 slot one previews but doesn't place (like the material workshop issue), the 12-slot also eats away pine planks needed for the construction and doesn't place down the warehouse.

Also I've noticed that the tooltip sometimes tells you that you have all the materials needed for the construction when it is not true.

**Comment by Ryddag** [comment]
How many warehouses you already have ? 5 is max

**Comment by Taisamba** [comment]
3 warehouses
