### ISSUE TITLE
Game stops functioning properly after trying to trade with someone from general chat.

### ISSUE THREAD

**Issue by PF2K** [ProjectCeleste/Celeste_Server#69]
As the title says, once you right click on someone's name and then press "trade", you get shown the "waiting for other player" screen and then even if you press cancel, nothing works. You're forced to relog. you can't even bring up the menu by pressing escape. You have to click on the cog thing on the top right of the minimap to bring it up.

**Comment by musictopia** [comment]
Currently, the trade is not even supposed to work yet.  I think the workaround for now is to not even use the trade until the developers say they got it working.

**Comment by Ryddag** [comment]
B102 seem to fix it.
