### ISSUE TITLE
cant finish a quest 

### ISSUE THREAD

**Issue by hansolo0002** [ProjectCeleste/Celeste_Server#72]
in a quest like *helping out a neighbor*  they say imust kill all enemy ,and i did kill them all but mission is not complite

**Comment by Ryddag** [comment]
have retryed todo it ?

**Comment by hansolo0002** [comment]
yes i have try to retry and  i have try also : long out and long in  ,**didnt work**  i have try install from mininstaller , **didnt work**, i download from steam the game files **didnt work**  i will post here a pick to show you what i mean 
![default](https://user-images.githubusercontent.com/29290509/26966555-37da4c36-4d03-11e7-9a5a-99b691199ebf.png)

**Comment by hansolo0002** [comment]
**here i have from ather quest** 
![2](https://user-images.githubusercontent.com/29290509/26980583-4445dbf6-4d3b-11e7-82ac-d2fdc9ecedbd.png)
