### ISSUE TITLE
Still impossible weapons in loot table

### ISSUE THREAD

**Issue by deefbert** [ProjectCeleste/Celeste_Server#73]
The loot table contains other things than weapons now, but still features impossible weapons (e.g. epics at level 7).

List with correct levels for items: https://aoeo4ever.net/handbook/gear.html

**Comment by Ryddag** [comment]
This table is incomplete, no one has the good one a lot of gear miss their lvl.

**Comment by deefbert** [comment]
Every droppable item on there seems to have the correct level indicated?

**Comment by jiffyette** [comment]
actually in the original game - beta , u could get a hammer of construction at lvl 10 . they changed it upon the game being sold

**Comment by musictopia** [comment]
I actually like that all gear can be obtained at all levels but the stats are just different.

**Comment by jiffyette** [comment]
+1 music

**Comment by onlinemindgem** [comment]
I dont like it... kills gameplay
Enjoy my vizer robe now for gastra but hmmm...

**Comment by jiffyette** [comment]
what lvl  ? hows it kill gameplay ? it makes levelling more fun
