### ISSUE TITLE
Windowed mode - widgets texture not load

### ISSUE THREAD

**Issue by francot514** [ProjectCeleste/Celeste_Server#74]
Im playing in windowed mode and when open the Gear, Advisor, Tech widgets got white texture.

![spartan 2017-06-08 17-41-15-11](https://user-images.githubusercontent.com/6117358/26953727-b8b4210c-4c71-11e7-9949-29a4518210b7.png)

**Comment by Semperfi0817** [comment]
For me it is every window I open:
![img_20170608_185900860](https://user-images.githubusercontent.com/29178199/26954275-09f0dcee-4c7d-11e7-85bd-278f2ca5c439.jpg)

**Comment by Ryddag** [comment]
Do you use the last dll ? the one from B101 zip file

**Comment by Semperfi0817** [comment]
Yes, the original.... I still have to CTL ALT to get to the login but when
I tried using the one pinned in the forum the game wouldn't let me in so I
changed back to the one from the Celeste zip.

**Comment by Ryddag** [comment]
try this one, user who use it seem to have the issue fixed, login is before game launch so no need clt alt : https://cdn.discordapp.com/attachments/314780359193788417/322138807187013632/Celeste_Client_B101.zip

**Comment by deefbert** [comment]
I get this for the Milestone background image.

**Comment by Semperfi0817** [comment]
I can now log on without having to ALT DEL but still have white on every
windows I open in game..

**Comment by Ryddag** [comment]
ok, its due to the new xlive.dll, i will fix it in next few day

**Comment by Ryddag** [comment]
B102 seem to fix it.
