### ISSUE TITLE
problems with eggy civ loading maps

### ISSUE THREAD

**Issue by jiffyette** [ProjectCeleste/Celeste_Server#75]
so im level 32, started cyprus, im having constant maps not loading textures properly.,  the buildings in the quests of tha AI are browned out - no colour, the shape is there, but all brown. if i finish the quest, it crashes sparta.exe. and i have to kill the process ( by signing out of windows)

also i have hathor and dumnorix to add to advisor hall, when i add hathor, then dumnox, the server kicks me out every time. please look into both, very annoying / frustrating to restart client every time i load a map that doesnt load properly

ty

**Comment by Ryddag** [comment]
B102 seem to fix it.
