### ISSUE TITLE
legendary capital store

### ISSUE THREAD

**Issue by MrPSIHO13** [ProjectCeleste/Celeste_Server#80]
ok here is funy thing,on eggy i get legendary store for capital
i placed it off course hehe and i see cypruss things inside,so i go 
to that region and cypruss shop have no items in it hehe (other things works fine)

**Comment by Ryddag** [comment]
Thx i will remove it from loot table.
Its normal that cyprus shop loose this loot, it has same id so it use same index and then conflict ^^

**Comment by MrPSIHO13** [comment]
no leave it just make some other gear in it hehe
