### ISSUE TITLE
Treasury Blueprint

### ISSUE THREAD

**Issue by doddianca** [ProjectCeleste/Celeste_Server#82]
This Blueprint will not set up within the capital city.

**Comment by musictopia** [comment]
I had the same issue with the sea people flag.  Could be a related problem to the sea people flag not being able to be placed.

**Comment by Ryddag** [comment]
I was able to place it.

http://imgur.com/a/56ysV

**Comment by doddianca** [comment]
Treasury NOW works after update 6/11/2017
