### ISSUE TITLE
item dont move or sell

### ISSUE THREAD

**Issue by matt60400** [ProjectCeleste/Celeste_Server#84]
I have an object that I can not move to sell or destroy.

a gear : Fine work clothing

its same for Delphi limestone

**Comment by lukipr0** [comment]
can't sell, place OR destroy these 3 cap city buildings (not even move them around in the inventory). same applies to my pine planks and stone blocks. i relogged several times, to no avail. also: when i sold something else i couldn't buy it back. i used something of no value to test this very thing.
![20170610142231_1](https://user-images.githubusercontent.com/29333820/27002838-6de36216-4deb-11e7-8af1-cca90dc8f2c7.jpg)
