### ISSUE TITLE
graphics issues

### ISSUE THREAD

**Issue by Khasp** [ProjectCeleste/Celeste_Server#85]
Processor: Intel(R) Core(TM) i5-6400 CPU @ 2.70GHz (4 CPUs), ~2.7Hz
Memory: 8192MB RAM
Graphics Card NVIDIA GeForce GTX 970
Display 1920 x 1080 (32 bit) (60Hz)

Units are flickering on the screen, screen flashes. Forced to play with shadow settings and other options turned on low and off and resolution 1280x720  so I have somewhat stable experience. The issues are still triggered a lot when I alt tab and it takes multiple alt-tabs to bring it back to somewhat normal.

I don't know if that is a known issue and what triggers it.

Uploading a small preview of how it looks with the flickering units. 

![image](https://user-images.githubusercontent.com/29333004/27002610-617e0fee-4de6-11e7-89eb-ddafc696f308.png)

**Comment by Ryddag** [comment]
B102 seem to fix it.

**Comment by Khasp** [comment]
Yes so far seems to be fixed ! Good job.

2017-06-12 2:08 GMT+02:00 Ryddag <notifications@github.com>:
