### ISSUE TITLE
Age of Empires Online doesn't respond after attempting to access the server.

### ISSUE THREAD

**Issue by Andres-Currea** [ProjectCeleste/Celeste_Server#87]
Hello. I've been trying to play for the last three days, but I haven't been able to. I've asked for help to two supporters, but still, I couldn't enter.
The problem is this: I launch the launcher and hit play, so the Celeste's logging in window appears. Then the game opens and I hit play. A little window appears saying something like "logging in  connecting to authorization server" and then the game stops responding. It even ignores attempts to cancel the log in.
I don't know if I should put this all here, but I need help.
What should I do?

**Comment by BOSAIF86** [comment]
Hello , which Anti-virus software do you use?

**Comment by Andres-Currea** [comment]
Avast. It's worked well until now. I anyhow tried playing after deactivating it. Still, the same problem happens.

**Comment by Ryddag** [comment]
B102 seem to fix it.
