### ISSUE TITLE
Can't complete "reclaiming the throne" quest.

### ISSUE THREAD

**Issue by Thin029** [ProjectCeleste/Celeste_Server#88]
Hello. I can't complete the "reclaiming the throne" quest. I pick up a reward, click complete but nothing happens. Already tried loging off and back in, restarting the game and even tried completing it on other PC with no luck :(.

Video: https://1drv.ms/v/s!AmapfsZM4scasfNEIHg_oyZhSdppfQ

**Comment by Thin029** [comment]
Tried abandoning the quest, finished it again but still can't complete. I am stuck really.

**Comment by Ryddag** [comment]
Can retry if the issue is still present with today update ?
