### ISSUE TITLE
Quest : trade for Giza limestone

### ISSUE THREAD

**Issue by MrPSIHO13** [ProjectCeleste/Celeste_Server#91]
BIG bug

infinity EXP bug see my video part 5 i think on YouTube (on end of it)
did from lvl around 23 to 40 in minutes :)

and still didnt get any giza :(
i need giza limestones hehe

**Comment by Ryddag** [comment]
If you found a bug you don't have to abuse it, just report it !!!!

**Comment by MrPSIHO13** [comment]
but i need giza,and i tried many other options,it wont give reward for quest complete

PS:i didnt temper with any files or services (same as new celeste installer on aoeo4ever)

**Comment by Enveee** [comment]
"but i need giza,and i tried many other options,it wont give reward for quest complete"

Yes you tried the same thing 50 times to go lvl 40 don't lie us dude.
you make a report to this bug and its a good thing for the futur of this game BUT a honest person like you think to be are use this bug 5 - 6 times maximum. not for go lvl 23 to 40.
Finally you go 40, k fine for you i 'don't care, but what I hate is the liars and the bad-faith people.

I think I would have had more respect for you if you simply reported the bug without wanting to pretend to be a honest person
