### ISSUE TITLE
Unable to get rewards from quest

### ISSUE THREAD

**Issue by musictopia** [ProjectCeleste/Celeste_Server#95]
I have found that if somebody completes a quest but don't have enough room in their inventory, instead of a messagebox saying don't have enough room in your inventory, it does nothing except give the experience points.  However, if you log off and log back on, it will show the quest complete and you get no reward except for the experience points.  What happened in the original game is if a player did not have room in their inventory, it would give a popup so a player is forced to make room in order to complete the quest.

**Comment by jiffyette** [comment]
it used to do that in the original game though,m if u had no room u missed out

**Comment by musictopia** [comment]
in the original game, it would give a popup letting a person know they don't have enough in inventory.

**Comment by Ryddag** [comment]
just tried online, if you inventory is full you can't complete the quest at all, their is no issue. And after logoff logon i can't complete it too, only when i set an slot free.

For the pop up who said inventory don't find out how to trigger it yet, don't sure if it was any in this case.
