### ISSUE TITLE
Quest Eliminating A Threat [GR] AI Villagers not working

### ISSUE THREAD

**Issue by ChewierElf** [ProjectCeleste/Celeste_Server#96]
The Greek Quest: "Eliminating A Threat" the villagers are just standing still and not coming into harvest action. While there is plenty berries around and a barracks the AI also does not seem to train a few additional bandits.
I understand the quest is early on in the progress ladder but perhaps a little more difficulty makes for a more challenge.
Only 2 bandits attack. 1 from left side and 1 from right side come into camp to attack early on ( +1 min into game play) and that's it. 
Maybe could use some tweaking this quest. Do not see more then 1 treasure bandit.
Not a high priority.
Hope this all helps.

**Comment by ChewierElf** [comment]
Additional info: Leaving the Villagers alive, since they are not doing anything but destroying all buildings and killing all bandits does give me completion on the quest trigger for "Enemies Defeated: Completed"
Which should be false. since as long as there are villagers around the enemy can start rebuilding. (Kinda).
Anyway hope this helps.

**Comment by musictopia** [comment]
I used to play this quest on the original game and I can honestly say this is how this one was designed.  Because its a tutorial quest.   So the AI was set where the ai does either very little or nothing at all. I think this quest should be left alone.

**Comment by ChewierElf** [comment]
I disagree with you Musictopia. The design of the quest was without villagers and with at least 2 treasure guardians. See youtube for proof. I spoke with the designer of this quest who made it. The idea is just do or do not implement the villagers. If you do then they should do something and not standing still doing nothing. What's the point of that? Has nothing to do if it is a tutorial quest or not. (_And what you think is personal assumption here is mine: I think you're influence changes way to many things of the original as you did on the penelope versions_). I would leave the decision making up to the quest developer on this one.

**Comment by Ryddag** [comment]
the quest work like it was designed.
