### ISSUE TITLE
chat not working

### ISSUE THREAD

**Issue by jiffyette** [ProjectCeleste/Celeste_Server#98]
ive now relogged 3 times from both civs, and chat isnt working :(

**Comment by jiffyette** [comment]
chat works fine on egg civ, but when i log out or quit the game and restart everything and log in using greek, i get the error " cannot connect to chat" in red writing :(

**Comment by Ryddag** [comment]
Fixed ? any other have this issue

**Comment by jiffyette** [comment]
let u know once server is restarted

**Comment by jiffyette** [comment]
chat is still buged on greek civ

**Comment by Toetje585** [comment]
Lets keep this open until we have a 100% working chat?

It's just a matter of time before the issue gets duplicated.
