### ISSUE TITLE
Epic consumable Special Ability: Heroic Aid falls 1 short

### ISSUE THREAD

**Issue by ChewierElf** [ProjectCeleste/Celeste_Server#99]
I've tried to see if this has been reported earlier but I could not find anything on it.
When going to the Empire Bazaar and speaking to Marcus Pollux he offers 2 quests. 1- The Golden Hippikon advisor card and the 2- "Wait, there's more".
From the latter one we have the choice of choosing the epic consumable "Special Ability:Heroic Aid"
He offers a stack of 5.
When turning in the quest I only received 4
I heard from a few other ppl in the game chat they got the same 4.
Marcus is getting rich and keeping 1 for himself.
Hope this helps.

**Comment by Ryddag** [comment]
It before last update i assume (one with inventory bug), because i tried 3 times (remove my character and recreate one) i always get 5.
